### ISSUE TITLE
GBR administrative area level 2 lost at level 3

### ISSUE THREAD

**Issue by RobertRosca** [covid19datahub/COVID19#100]
The level 2 region data is lost at level 3, I'm pretty this wasn't the case before.

Before you could download the level 3 GBR data, then filter by level 2 by `England`, and then get all the level 3 regions in England. Now if you pull the level 3 data in the level `administrative_area_level_2` column is empty, so there's no way to select a level 2 area and then filter level 3 by that selection.

**Comment by eguidotti** [comment]
Hi @RobertRosca, thanks for your message.
Yes I'm aware of this. The GBR source is producing Internal Server Errors at the moment and the data are temporary disabled.
Hope they will be back soon

**Comment by RobertRosca** [comment]
Ah alright, hopefully they'll fix their issues soon, thanks for the quick reply!

**Comment by eguidotti** [comment]
It seems the data are back again :)
