### ISSUE TITLE
Level 3 Clean csv Data Not Loaded

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#101]
Hi, the level-3 cleaned csv data are not loaded and never backed up yesterday ( https://storage.covid19datahub.io/data-3.csv )

Thank you. Ken

**Comment by eguidotti** [comment]
The backup is generated after 2 days in order to make sure worldwide data for the given day are complete. 
This means the backup for yestarday (8/24) will be available tomorrow (8/26).
Regarding the level 3 data please see #102 
Thank you
