### ISSUE TITLE
Level 3 Data Not Updated

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#102]
The level 3 data I referenced earlier are now there, nut have not been updated since 8/22.

**Comment by eguidotti** [comment]
Hello @kenshermock, this is weird as no changes were made in the hub and the data seems to be there up to 8/24.
Also the backup on 8/23 seems correct and contains the data up to 8/23. 
```R
# make sure to use the CRAN version
install.packages("COVID19")

# load the package
require("COVID19")

# download
x <- covid19("USA", level = 3, raw = T) # latest data
x <- covid19("USA", level = 3, raw = T, end = "2020-08-23", vintage = T) # backup on 2020-08-23
```
Is it maybe a caching issue? In case your program is running continuously for several days please make sure to disable cache by setting `cache=FALSE` in the `covid19()` function. Hope this helps

**Comment by kenshermock** [comment]
Thank you, Emanuele,

I’m not sure what happened. I ran the same code I’ve been using for months. I even verified that nothing was there when I manually clicked the link to the csv. This morning, everything is back to normal and the data uploaded to my computer, current thru 8/24. Thank you for your efforts.

Ken

**Comment by eguidotti** [comment]
No problem. Happy it works and thanks for your continuous feedback.
Emanuele
