### ISSUE TITLE
Coordinates for Denmark and France are wrong

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#119]
Hi! Just wanted to notify that the lat/long coordinates for Denmark and France as delivered with the country timelines are off. Maybe this is due to their overseas territories. If you run a geo algorithm searching for the center point of a country polygon, you end up with a point in the middle of nowhere if you forget to delete the overseas polygons first. So the point for Denmark is somewhere in the north Atlantic and the point for France is in western Africa. 

France could be 46 lat 3 long
Denmark could be 56 lat 9 long 
(EPSG:3857 Web Mercator)

**Comment by eguidotti** [comment]
Hi @guenterhack, many thanks for spotting the errors.
Should be fixed now.
Thanks!

**Comment by guenterhack** [comment]
Thank you very much for your swift reaction!
