### ISSUE TITLE
The JHU US data is by state and county - there is no city level data

### ISSUE THREAD

**Issue by rowrowrowyourboat** [covid19datahub/COVID19#12]
The readme file says that the JHU data is at the state and city level, but it's at the state and county level.

**Comment by eguidotti** [comment]
Could you please clarify were you see that the JHU is at state and city level in the README? 
I could't find it. Am I missing something?

**Comment by rowrowrowyourboat** [comment]
readme line 181

**Comment by eguidotti** [comment]
Those are the data for the US from JHU. They are of the type:
Washington, Alabama, US
Our convention is 

- US: level 1 (country)
- Alabama: level 2 (state)
- Washington: level 3 (city)

Maybe some concerns about the naming 'city'?

**Comment by rowrowrowyourboat** [comment]
Yeah, 'city' is misleading, vs calling it 'county' is more accurate and could prevent confusion.  Or just call them admin level 1, admin level 2, admin level 3, etc. to prevent any confusion about what is actually being presented.

**Comment by eguidotti** [comment]
Yes thanks, updated.
