### ISSUE TITLE
wrongly formated key_numeric in US data

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#121]
Hi,
The "key_numeric" data is incorrect in the admin level 3 US data: it is formatted as an integer instead of a character and is loosing digits. These are FIPS codes, and should be 5 digits at the county level. For example, Autauga County in Alabama is FIPS code "01001", but it is entered in the covid19 data hub as 1001. I'm not familiar with other countries, but similar problems may exist in other geographies as well.
Fixing this would make life easier...thanks for the great product!

**Comment by eguidotti** [comment]
Hi @hlcny, thanks for your message.
The `key_numeric` codes are in the correct format. It should be `numeric` as stated in the column name.
You can easily add leading zeros by e.g.:
```R
library("COVID19") # load the package
x <- covid19("USA", level = 3) # download the data
sprintf("%05d", x$key_numeric) # add leading zeros
```
Hope this helps
