### ISSUE TITLE
Partially missing level 2 data for Germany

### ISSUE THREAD

**Issue by AlFontal** [covid19datahub/COVID19#125]
Hi, first of all, thanks for putting together this awesome tool. 

I am trying to run an analysis using time-series data for the confirmed cases in German landers. I am using the Python API but I also double-checked with the R API and I am getting the same:

```python
covid_germany, _ = covid19(['Germany'], level=2, verbose=False)
print(covid_germany.administrative_area_level_2.unique())
```
```
['Bayern' 'Schleswig-Holstein' 'Nordrhein-Westfalen' 'Baden-Württemberg'
 'Bremen' 'Hamburg' 'Hessen' 'Rheinland-Pfalz' 'Niedersachsen']

```
So basically, I can only fetch data for 9 out of the 16 landers. Missing the regions in red: `['Saarland', 'Berlin', 'Sachsen-Anhalt', 'Thüringen', 'Brandenburg', 'Sachsen', 'Mecklenburg-Vorpommern']`

![image](https://user-images.githubusercontent.com/10958332/97574071-fcd82f00-19ea-11eb-8448-be4fdc3f179f.png)

The source, [RKI](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/ef4b445a53c1406892257fe63129a8ea_0), seems to report for all landers, so where is this data getting lost?

**Comment by eguidotti** [comment]
Hello @AlFontal and thanks for your feedback!
It seems the data provider was not updating correctly, but now everything seems back to normal.
No changes were made on our side on the integration of German data.

I get all 16 landers in R:
```R
# install.packages("COVID19")
library("COVID19")
x <- covid19("Germany", 2)
unique(x$administrative_area_level_2)
```

Hope this helps!

**Comment by AlFontal** [comment]
Hi @eguidotti,

Thanks! I did check and indeed I now get data for all the expected landers. Closing the issue.
