### ISSUE TITLE
Data for Austria is outdated

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#128]
Hi!
I just wanted to report that the data for positive tests in Austria in the admin level 1 file has not been updated for three days. Where do you source the data for Austria? JHU has different numbers for the positives, at least in the time series. 

JHU: 
10-27: 86102
10-28: 89496 
10-29: 93949

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

Covid-19:
2020-10-27: 91386
2020-10-28,: 94891
2020-10-29: 94891
2020-10-30: 94891

https://storage.covid19datahub.io/data-1.csv

The official data provider for Austria would be the federal health agency AGES: https://covid19-dashboard.ages.at/dashboard.html and the URL of the relevant data CSV is https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv (Filter for "Österreich" in the column "Bundesland" and take the latest data from the column "AnzahlFaelle". 

I know that there seems to be a problem with data transfer from Austria to ECDC. Do you source it from there?

All the best from Vienna!
gh

**Comment by eguidotti** [comment]
Hi @guenterhack, thanks for your message!
The data for Austria are from the same source you suggest, but a different file:
https://www.data.gv.at/katalog/dataset/fdff55f1-2157-49df-a351-b696ab3d471a

It was the only available some time ago, I see now they are providing more and better datasets. I changed the source file to the one you suggest and added hospitalizations, tests and ICU for both admin levels 1 and 2.
Still, there seem to be some slight mismatches among JHU, wikipedia, AGES dashboard and AGES data files. 

I believe you have more sensitivity on the data for Austria than I do. Would you mind double checking the data are now correct?
```R
x1 <- covid19("AUT", 1)
x2 <- covid19("AUT", 2)
```
Many thanks!

**Comment by guenterhack** [comment]
Dear Emanuele, 
thank you for your help! I've imported the file and it is correct. It was good to change to the new source csv anyway, because the "older" files will only be maintained until the end of the year. The new files are:

CovidFaelle_GKZ.csv
New positives and deaths on admin level 3 ("Bezirke", one unit below "Bundesland" (federal states like Vienna or Tyrol))
Bezirk;GKZ;AnzEinwohner;Anzahl;AnzahlTot;AnzahlFaelle7Tage

CovidFaelle_Timeline.csv
New positives, deaths, recovered on admin level 2
Time;Bundesland;BundeslandID;AnzEinwohner;AnzahlFaelle;AnzahlFaelleSum;AnzahlFaelle7Tage;SiebenTageInzidenzFaelle;AnzahlTotTaeglich;AnzahlTotSum;AnzahlGeheiltTaeglich;AnzahlGeheiltSum

CovidFaelle_Timeline_GKZ.csv
Positives, deaths, recovered on admin level 3
Time;Bezirk;GKZ;AnzEinwohner;AnzahlFaelle;AnzahlFaelleSum;AnzahlFaelle7Tage;SiebenTageInzidenzFaelle;AnzahlTotTaeglich;AnzahlTotSum;AnzahlGeheiltTaeglich;AnzahlGeheiltSum

CovidFallzahlen.csv
Tests, hospitalized, ICU, free hosp and ICU beds per admin level 2 and admin level 1 ("Alle").
Meldedat;TestGesamt;MeldeDatum;FZHosp;FZICU;FZHospFree;FZICUFree;BundeslandID;Bundesland


The Austrian case data has the following characteristics:
a) The CSV on state level shows epidemic curves, so daily entries might change over time with every new file. Formerly there was no real timeline, only new cases per day.
b) The CSVs are updated daily at 14:00 CET. For the current date, they show the new cases collected until 13:00 CET on that day. So if you want to calculate the usual 7- or 14-day incidence you better skip the latest row of data or take the (correctly calculated) incidence from the incidence column. Because of the incidence problem, there will be a switch to reporting only data from the day before, omitting the current day. I don't know when this will happen. 

Yours sincerely
Guenter

**Comment by eguidotti** [comment]
Dear Guenter,
many thanks for your detailed message.
I'm now working on the Austrian case and I'd like to implement all the data available for levels 1, 2 and 3. It would be great if you could help me with the following questions:

- I tried to translate but I'm not sure about the cumulative number of deaths in the CovidFaelle files. Is it maybe the column `AnzahlTotSum`?
- national level number of deaths from `CovidFaelle_Timeline.csv` on 30.10.2020 is 1079. From `TodesfaelleTimeline.csv` it is 1031. Which file is correct?
- national level number of recovered from `CovidFaelle_Timeline.csv` on 30.10.2020 is 56155. From `GenesenTimeline.csv` it is 64987. Which file is correct?

Many thanks!

**Comment by guenterhack** [comment]
a) AnzahlTotSum is correct
b) Please use CovidFaelle_Timeline.csv. It uses the WHO method of determining Covid-19 death cases, the older file uses an Austrian definition which is somewhat more strict (Covid-19 has to be confirmed as sole cause of death by official coroner)
c) If in doubt, use CovidFaelle_Timeline.csv, it's exported daily directly out of the central epidemy database (Epidemiologisches Meldesystem; EMS) - and it won't expire at the end of the year. That said, I know that the local health authorities tasked with data entry are currently overwhelmed by the "second wave" and are in retard with data entry. The deprecated file contains more of an estimate which could be a bit more correct, at the moment. 

I'm a bit at a loss, because there is no Englisch documentation of the file structure. There should be one.

**Comment by eguidotti** [comment]
Up and running! Added full support for levels 1, 2 and 3 from `CovidFaelle_Timeline.csv`, `CovidFaelle_Timeline_GKZ.csv`, and `CovidFallzahlen.csv`. Please close the issue if this works for you. 
```R
x1 <- covid19("AUT", 1)
x2 <- covid19("AUT", 2)
x3 <- covid19("AUT", 3)
```
Thank you for your help and improving the data hub

**Comment by guenterhack** [comment]
Sorry to bother you again, but there is still a problem with the data. It's one day behind and omits yesterday's data. The problem is, as always, that the authorities are still writing a half day of data for the current date. So when I use Covid-19, I get:

2020-10-24,81948
2020-10-25,84333
2020-10-26,87019
2020-10-27,91312
2020-10-28,95594
2020-10-29,100298
2020-10-30,101443
2020-10-31,101443

In the AGES file downloaded just now, I get: 

Datetime                   cases   sum cases
24.10.2020 00:00:00 | 2931 | 81942
25.10.2020 00:00:00 | 2385 | 84327
26.10.2020 00:00:00 | 2686 | 87013
27.10.2020 00:00:00 | 4310 | 91323
28.10.2020 00:00:00 | 4340 | 95663
29.10.2020 00:00:00 | 4877 | 100540
30.10.2020 00:00:00 | 5143 | 105683
31.10.2020 00:00:00 | 901 | 106584

The data is an epidemic curve, it changes every day retrospectively, because they are backdating new cases and deaths, so it doesn't work to import only the latest record. You'd have to import the whole file every day on, say, 14:30 MEZ. The latest date, the 31st, only gives the data for 0:00 to 13:00. This is a nightmare, but what isn't, nowadays...

**Comment by eguidotti** [comment]
Hello @guenterhack, I'm happy to inform you that the data hub is already importing whole files every hour. So that it works also for changes applied retrospectively. We also take snapshots of the data each day, so it is possible to detect and recover changes in the data applied retrospectively. See the vintage data e.g. [here](https://covid19datahub.io/articles/data.html) or the `vintage` argument in the R/Python packages.

> In the AGES file downloaded just now, I get:

I tried just now using `covid19` and I get the same data. Probably the update was not completed yet when you tried. Would you mind checking one more time?

**Comment by guenterhack** [comment]
I wrote an ultra-crude test script (I'm a total R n00b, forgive me). I also had to remove comments, because the system interprets them as text formatting.

---

`
library(COVID19)
library(dplyr)


x1 <- covid19("AUT", 1)

austria <- read.csv("https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv", head=TRUE, sep = ";", fileEncoding = "UTF-8-BOM", stringsAsFactors = F)
austria <- dplyr::filter(austria, Bundesland == "Österreich")
austria <- head(austria,-1)

austria <- tail(austria,7)
x1 <- tail(x1,7)

compare <- cbind(austria$Time,austria$AnzahlFaelleSum,as.character(x1$date),x1$confirmed)
colnames(compare) <- c("Timestamp AGES","Confirmed AGES","Timestamp Covid-19","Confirmed Covid-19")

`
---

If I run it now, I get:

Timestamp AGES | Confirmed AGES | Timestamp Covid-19 | Confirmed Covid-19

24.10.2020 00:00:00 | 81942 | 2020-10-24 | 81948
25.10.2020 00:00:00 | 84327 | 2020-10-25 | 84333
26.10.2020 00:00:00 | 87013 | 2020-10-26 | 87019
27.10.2020 00:00:00 | 91323 | 2020-10-27 | 91312
28.10.2020 00:00:00 | 95663 | 2020-10-28 | 95594
29.10.2020 00:00:00 | 100540 | 2020-10-29 | 100298
30.10.2020 00:00:00 | 105683 | 2020-10-30 | 101443

**Comment by eguidotti** [comment]
Hello @guenterhack. This is probably due to 1 hour lag or so between the update of AGES and update of the data hub.
Running it now I get exactly the same values. You can test with e.g.:

```R
# Please make sure to use the CRAN version of the package. Install with:
# install.packages("COVID19")

library(xts)
library(COVID19)

x <- covid19("AUT", 1)
x <- xts(x$confirmed, order.by = x$date)

a <- read.csv("https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv", head=TRUE, sep = ";", fileEncoding = "UTF-8-BOM", stringsAsFactors = F)
a <- a[a$BundeslandID==10,]
a <- xts(a$AnzahlFaelleSum, order.by = as.Date(a$Time, format = "%d.%m.%Y"))

xa <- cbind(x, a)
plot(xa, legend.loc = "topleft") # should display 2 overlapping lines
View(xa) # view the data 
```

**Comment by guenterhack** [comment]
Thank you, Emanuele! Now it works perfectly! Just allow me one more question: When/how often do you export the CSV file for admin level 1 to this location? https://storage.covid19datahub.io/data-1.csv

**Comment by eguidotti** [comment]
All the admin levels are exported once per hour in usual circumstances. When updating the data hub it may take some more time, but in any case all the files are refreshed multiple times per day. If you find this is not the case, please open an issue. There might have been a failure in the pipeline. I'm now going to close the issue, happy it works and thanks for your help!

**Comment by guenterhack** [comment]
Hi! Just to let you know: The Austrian health agency has modified their files today and they are now omitting the "half" day for the current date. So they are exporting CovidFaelle_Timeline.csv until yesterday's timestamp. I think that's a better solution.
