### ISSUE TITLE
Regional Data for France is broken

### ISSUE THREAD

**Issue by AlFontal** [covid19datahub/COVID19#129]
Hi again! New day, new country I found with missing data!

It seems that the [source for regional data in France](https://github.com/opencovid19-fr/data/), at least at the administrative level 2, is broken, only producing data for some days of March and April.

There is [an issue](https://github.com/opencovid19-fr/data/issues/544) open about that which is at least a month old, but it has not been addressed yet. Any ideas on how to fix this?

**Comment by eguidotti** [comment]
Hi @AlFontal, thanks for spotting this. 
I just left a comment in that issue. It seems the variables affected are the number of confirmed cases and number of tests. Unfortunately I can do nothing about it. Can you suggest another data provider for France level 2?

**Comment by AlFontal** [comment]
I have tried but it seems that all the official sources are not providing this. [This](https://www.data.gouv.fr/fr/datasets/chiffres-cles-concernant-lepidemie-de-covid19-en-france/) is the main source being used and the regional data is missing in both the CSV and JSON files, so I am guessing this might be an upstream problem and pretty hard to do anything about it from our side...

**Comment by eguidotti** [comment]
Hi @AlFontal, thanks for the information. I'm going to close this issue. This is pretty sad though. Please don't hesitate to re-open this or another issue if you happen to come across a data source for regional data in France. Thanks!

**Comment by AlFontal** [comment]
I definitely will, thanks for the hard work!
