### ISSUE TITLE
Germany data is off by a factor of 10

### ISSUE THREAD

**Issue by vzemlys** [covid19datahub/COVID19#130]
Noticed today (2020-11-01) that Germany confirmed cases decreased. The last day (2020-11-01) reporst 45148 cases. I did a check an all other sources point to a number more close to ~500k.

**Comment by eguidotti** [comment]
Hi @vzemlys, thanks for your message. You are right, the data for Germany make no sense.
I just found out the the RKI-URL is broken and is returning only a fraction of (random?) data. They now recommend an alternative csv-link… [this one](https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data).
I updated the data hub and connected to the new RKI recommended URL.
You should be able to get the correct data in an hour or so. Please let me know if this works for you.

**Comment by vzemlys** [comment]
Not a problem. Thanks for your hard work.
