### ISSUE TITLE
Level 3 data have not updated since November 3. 

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#132]

**Comment by eguidotti** [comment]
Hello @kenshermock and thank you once again for your continuous feedback!
I have been double-checking the issue but it seems everything is working fine this time. 
Would you mind making sure you are not using a cached version of the data and let me know if the problem is still there?
```R
x <- covid19("USA", level = 3, cache = FALSE)
```
Many thanks!

**Comment by kenshermock** [comment]
Hi Emanuele,

I just tried to import again and it is not updated beyond November 3. I was able to import the level 2 data set updated to November 4. Thanks for all you are doing!

Ken

**Comment by eguidotti** [comment]
Thanks for the update. This is weird, I'm getting the latest data and also the automatic tests are completing successfully. It looks like a caching issue on your local machine (?). Would you mind trying to read this file by appending a random string in the end?

https://storage.covid19datahub.io/rawdata-3.csv?ue7ehr8r

This makes sure you are retrieving a non-cached version of the data file. If this works for you, I'm going to update the package with this fix. Thanks!

**Comment by kenshermock** [comment]
Thank you, Emanuele,

I tried an intermediate step and found something potentially useful. I typically import this file: https://storage.covid19datahub.io/data-3.csv

Since you instructed me to import the rawdata file, I tried importing https://storage.covid19datahub.io/rawdata-3.csv , and it was updated to November 4, which is what I would expect at this time of the day. So maybe there is a problem in the pathway from the rawdata-3 file to data-3?

Ken

**Comment by kenshermock** [comment]
The file you referenced below also were imported, updated up to Nov4. Thank you, Ken

**Comment by kenshermock** [comment]
It now seems that the level 2 file is not updating, either. I use the https://storage.covid19datahub.io/data-2.csv file and it is almost always updated by this time. Currently, it is updated only to November 4. Just in case this helps.   Ken

**Comment by kenshermock** [comment]
And still the file https://storage.covid19datahub.io/data-2.csv has not updated for Nov 5 . It is always updated at this time. FYI.

**Comment by kenshermock** [comment]
Sorry for all the messages, but I was able to download an updated copy of level 2 within the past 15 minutes: https://storage.covid19datahub.io/data-2.csv

Have not tried level 3 yet. Keep you posted. Thanks for all you do for this community of data scientists!

**Comment by kenshermock** [comment]
Level 3 file just updated to (to Nov 4, which is what I would expect at this time of night). Thank you. I hope I have not gotten on your nerves too much. I truly appreciate, and rely on, your diligent work. Best, Ken

**Comment by eguidotti** [comment]
Hello @kenshermock, no problem at all! Your feedback is always very much appreciated.
In case you are downloading the data by clicking the link on the website, I suggest to append a random query string to the URL., e.g. `https://<url-to-data-file>?<randomstring>`,  This makes sure you bypass the browser cache. 
Happy it worked!

**Comment by eguidotti** [comment]
Hello @kenshermock, I'm happy to inform you that I setup some metadata to instruct the browsers not to cache the files. 
You should be able to get the freshest data out of the box now.
Cheers
