### ISSUE TITLE
Level 2 not updated. Last update 11/7. These data are all the more important with the current surge.

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#133]

**Comment by eguidotti** [comment]
Hello @kenshermock, I just tried and I get the correct data up to 11/8.
It seems to be the same issue as in #132 
Which software are you using to retrieve the data? The [R package](https://covid19datahub.io/articles/api/r.html), [Python module](https://covid19datahub.io/articles/api/python.html), or clicking on the links on the [webpage](https://covid19datahub.io/articles/data.html)?
Thanks!

**Comment by kenshermock** [comment]
I import the data by weblink thru Stata. What I notice, even this evening, is that there is an 11/11 value for each county and each state. But they are the exact same value as 11/10. So it seems that there is still some update issue on your end. I hope this helps and I am grateful for all you do.

**Comment by eguidotti** [comment]
The values are filled with the previous day if the source is not updated yet. If you want to prevent this behaviour I suggest to use the `rawdata` file. The `data` files are pre-processed as described [here](https://covid19datahub.io/articles/data.html). I also suggest to append a random string `?randomstring` to the URL so to make sure to bypass (Stata?) cache.
In any case, today there was an issue with France and Australia. Many countries are changing the access to their data in this second wave. This is fixed now and everything should work as usual. Best
