### ISSUE TITLE
Colombia data is not working

### ISSUE THREAD

**Issue by Landa94** [covid19datahub/COVID19#136]
I checked the source from the Columbian government that you cite in the documentation and the information differs substantially from the one downloaded through the R package. 

Any ideas of what could be going on? 

Best

**Comment by eguidotti** [comment]
Hi @Landa94, thanks for your message! 
That's weird, we are downloading the data from the "plataforma de datos abiertos del gobierno colombiano API":
https://dev.socrata.com/foundry/www.datos.gov.co/gt2j-8ykr

Which source are you comparing with? That would help me to understand what could be going on.
Thanks!

**Comment by eguidotti** [comment]
Fixed. The data are now tha same as https://coronaviruscolombia.gov.co/
Also added `tests` for levels 1 and 2.
Thanks!
