### ISSUE TITLE
Data lag in Austria

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#137]
Hi!
Just wanted to tell you that the data for Austria on level 1 is lagging a bit. Seems like data for the 24th hasn't been imported yet. 
All the best
Guenter

**Comment by eguidotti** [comment]
Hi @guenterhack! Thanks for your message. Unfortunately it seems the source data files are not updated on 25.11.2020 even if the [dashboard](https://covid19-dashboard.ages.at/dashboard.html) says it is updated as of 25.11.2020 14:02:01, see e.g.:
https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv
Maybe is there a lag between the online dashboard and the update of their data files? Let's see how this works tomorrow

**Comment by guenterhack** [comment]
Hm. I just checked the latest updates. Covid-19 seems to have stopped ingesting new Austrian Data on 2020-11-24. The latest data has just been published (it is published daily on 14:07) and both the zip file and the url (as above) show the correct data e.g. sum of positive cases for 2020-11-25 is  264692. You're ingesting the data every hour, afaik, so the new data should have been imported today at 15:00.

**Comment by eguidotti** [comment]
Oh I see. We are ingesting the data every hour yes, but not on minute 00. For example the last run was on 14:55. Then it takes some time to process all the data worldwide and the release takes place only when everything is ready. The more data we add, the longer it takes. At the moment, the whole workflow takes a bit less than 1 hour. So if we are lucky the data provider updates at 14:07; we update at 14:08 and the data are available around 15. If we are not lucky, the provider updates at 14:07, we update at 14:55 and I'm confident that they will appear around 16 max :) If this is not the case, we have a problem!

**Comment by guenterhack** [comment]
Ah! So it was a latency issue. The newly imported data as of 16:00 CET is correct. Thank you, Emanuele!

**Comment by eguidotti** [comment]
Great, happy it works :)
