### ISSUE TITLE
Lithuania data is not updating

### ISSUE THREAD

**Issue by vzemlys** [covid19datahub/COVID19#138]
The Lithuania data is stuck at the same data for the last 3 days. It might be because from 11-25 the data is anounced in Lithuanian department of statistics: https://osp.stat.gov.lt/praejusios-paros-covid-19-statistika.

It has arcgis dashboard with the geojson for cases, recovered and deaths: 
https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/3df1e86f5235498ab7cf9cec615a7fd7_0

and for tests data:
https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/538b7bd574594daa86fefd16509cbc36_0

Alternatively you can fetch all the data in nice joined format from here:

country: https://github.com/mpiktas/covid19lt/blob/master/data/lt-covid19-country.csv
admin_level2: https://github.com/mpiktas/covid19lt/blob/master/data/lt-covid19-level2.csv
admin_level3:  https://github.com/mpiktas/covid19lt/blob/master/data/lt-covid19-level3.csv

The data in the first source is renewed at 9:30 each day. Geojson have a day lag. 

The data in the second source is renewed at 10:00 each day. It fetches the data from geoservice and goes around 2000 arcgis record limitation. Then joins everything nicely. The pipeline is run in gitlab: https://gitlab.com/vzemlys/covid19lt/-/pipeline_schedules

**Comment by eguidotti** [comment]
Hi @vzemlys, thank you for your detailed message!
This is very helpful, I think we are going to work on that as soon as done with the other 2 issues that ore opened at the moment.
Thanks!

**Comment by vzemlys** [comment]
Any news on this? The data for Lithuania is misleading. Unexplained jumps and whatnot. The sources I cited for open data is the official data from the Lithuanian statistical department, which is by law (I can dig up the exact law if necessary) the only institution which provides the official covid-19 data. So it is really frustrating that this source is not used. If there is a need I can write up the PR for using this source. Is there any documentation for this?

**Comment by eguidotti** [comment]
Sorry @vzemlys, let's try to catch up!
I tried to access the arcgis links that you posted above some time ago. They do not seem to work any longer.
So I'm wondering where the data in the joined format are coming from. I checked the [README](https://github.com/mpiktas/covid19lt) of the repo and I read:

> All the data is fetched from Statistics Lithuania.

Howevere the link for Statistics Lithuania seems to be broken.

Can you please post again the links to the official data? Or maybe provide some more details on the repository as the joint format looks nice and easy to integrate. Then I think we can directly set up the PR. But if you prefer, you can find a quick tutorial [here](https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source).

Thanks!

**Comment by vzemlys** [comment]
Sorry for the links, they do change from time to time. I fixed the README.

The data is fetched daily from the links below, I have pipeline in Gitlab on a daily schedule which runs the download and data combination and also generates the my own [dashboard](https://mpiktas.github.io/covid19lt/). You can check the commit history for the main data files. The main files are generate by the [code]( https://github.com/mpiktas/covid19lt/blob/master/R/create_levels.R), which uses the files which are downloaded by the following [code](https://github.com/mpiktas/covid19lt/blob/master/R/makefile_osp_live.R).


The main link to the datasets provided by department of statistics is the following:
https://open-data-ls-osp-sdg.hub.arcgis.com/search?collection=Dataset&tags=covid%2Cevrk2

The data drives the official dashboard: https://osp.maps.arcgis.com/apps/MapSeries/index.html?appid=c6bc9659a00449239eb3bde062d23caa.

The link for case data is the following:
https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/45b76303953d40e2996a3da255bf8fe8_0

The link for tests data is the following:

https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/07dce7d43ba04a5b93abbbbe1d20d9ea_0

The vaccination data set (by person):

https://open-data-ls-osp-sdg.hub.arcgis.com/datasets/ffb0a5bfa58847f79bf2bc544980f4b6_0

I've read the documentation the PR seems straightforward, I only need to find time to implement it :) All the data however comes in json format, so there is a need for dependency on `jsonlite` and `httr` packages. Is that a problem?

**Comment by eguidotti** [comment]
The package already depends on `jsonlite` and `httr` so you can use them without any problem. 
However I can see they also offer nicely formatted csv files that may be easier to integrate. For example for the tests:
https://opendata.arcgis.com/datasets/07dce7d43ba04a5b93abbbbe1d20d9ea_0.csv

> I only need to find time to implement it :) 

Sure! Let us know if you need help on this, @esuess should be able to help you out.

**Comment by eguidotti** [comment]
Fixed, thanks! The data are now available
