### ISSUE TITLE
The Value of "confirmed" decrease

### ISSUE THREAD

**Issue by terrytsaistats** [covid19datahub/COVID19#141]
If the variable confirmed is cumulative why does some of them decrease? I tried to create new cases but end up getting some negative numbers. Thank you for your help!

**Comment by eguidotti** [comment]
Hi @terrytsaiecon and thanks for your message!
What you notice is definitely true. On the [website](https://covid19datahub.io/articles/data.html) we provide a [rawdata.log](https://storage.covid19datahub.io/rawdata.log) where we list errors of this kind (errors in the raw data from the provider). Unfortunately, this does not depend on us but on the data provider. Even for official sources the data quality raises some concerns and some countries may provide noisy data. You can find [here](https://storage.covid19datahub.io/src.csv) the data sources we use. In R you can easily find them by:
```R
x <- covid19()
View(covid19cite(x))
```
I would encourage you to contact the provider or check on their website for possible explanations. And feel free to suggest a better provider for the data you are studying in case there is one.
Many thanks!

**Comment by eguidotti** [comment]
Hi @terrytsaiecon, if this is OK I'm going to close the issue thanks

**Comment by terrytsaistats** [comment]
Yes of course. Thank you for your help!
