### ISSUE TITLE
Support for number people who have been vaccinated.

### ISSUE THREAD

**Issue by artidataio** [covid19datahub/COVID19#142]
The news are out. Approved vaccines are being rolled out in many places. I hope this repo will support it as well.

**Comment by eguidotti** [comment]
Hi @artidata, great idea! Feel free to post here the links to the official data repositories you come across. Thanks!

**Comment by GuidoMaggio** [comment]
https://ourworldindata.org/covid-vaccinations

world vaccines data by country seem to be collected here

**Comment by eguidotti** [comment]
Up and running! Everything is up to date with the new data on vaccines.
I'll keep the issue open for a while. Just in case someone else wants to add further suggestions and resources about this.
Thanks a lot for sharing!

**Comment by lisphilar** [comment]
FYI.
My Python package, Covisirphy, retrieves vaccination data from "Our World In Data" @GuidoMaggio mentioned.
Python codes: https://github.com/lisphilar/covid19-sir/blob/master/covsirphy/cleaning/vaccine_data.py

 I have little knowledge about R language, but we can share Python codes.

**Comment by eguidotti** [comment]
Hi @lisphilar, thanks for sharing. I already implemented the vaccine data from "Our World in Data" as suggested by @GuidoMaggio. I guess you should be able to get them with `covid19` as usual

**Comment by lisphilar** [comment]
Oops, I misunderstood. Thank you for your work always.

**Comment by GuidoMaggio** [comment]
I forgot to mention THANKS
