### ISSUE TITLE
french data 2020 january wrong

### ISSUE THREAD

**Issue by oberhamsi** [covid19datahub/COVID19#145]
there's a problem with the french data from 2020 january: recovered, deaths & hosp are very high and obviously wrong.

![image](https://user-images.githubusercontent.com/53384/103534261-d6bd8800-4e8e-11eb-8f71-518f436156dd.png)

**Comment by eguidotti** [comment]
Hi @oberhamsi, thanks for your message!
It seems this was due to the source repository for French data. Maybe something was messed up with 2021.
I fixed this on our side. You should get the latest data in a couple of hours. 

I also notified the original repo here
https://github.com/opencovid19-fr/data/issues/563

Thanks!

**Comment by Inglezos** [comment]
I am afraid the problem unfortunately remains:
![image](https://user-images.githubusercontent.com/36845191/104021557-a6942300-51c7-11eb-888a-e456559e5ce0.png)

**Comment by eguidotti** [comment]
Hi @Inglezos, I fixed it again on our side.
You should get the latest data in a couple of hours.

The real issue is with the source repo. I updated here 
opencovid19-fr/data#563

Hope this helps!

**Comment by Inglezos** [comment]
Thank you very much!
Will you be able to keep preprocessing and correcting these data from your side daily until the source repo updates its implementation and fixes this?

**Comment by eguidotti** [comment]
It should be already fixed until 24 January on our side, after that date I'm afraid the source repo may start to overwrite last year data with 2021 and more drastic solutions may be needed (i.e. changing the data provider). But let me know in case you still see some issues with the data. Thanks!

**Comment by Inglezos** [comment]
Okay I will be checking France data regularly then and I will let you know if something comes up, thank you again for the support.
