### ISSUE TITLE
Weird tests spike in Austria

### ISSUE THREAD

**Issue by Inglezos** [covid19datahub/COVID19#147]
I noticed that there is a weird spike in Austria testing records for past few days, there were added almost 3 million tests in one day on 12Jan21, which is improbable:
![image](https://user-images.githubusercontent.com/36845191/104629340-0ac05680-56a2-11eb-979e-54ab97f0e20d.png)
Could you please investigate why this is happening?

**Comment by eguidotti** [comment]
Hi @Inglezos, it definitely looks weird. 
However, the data are those reported by Federal Ministery of Social Affairs, Health, Care and Consumer Protection, Austria (BMSGPK). 
Here the link to the source file: https://covid19-dashboard.ages.at/data/CovidFallzahlen.csv
And the dashboard: https://covid19-dashboard.ages.at/

I believe you can try to contact them directly. I see this email address on the webste: covid19-dashboard@ages.at
Thanks!

**Comment by Inglezos** [comment]
Thank you for the detailed response. I will send them an email, let's hope they will reply or solve this soon. I will let you know if I have any news.

**Comment by eguidotti** [comment]
Yes please keep me posted on this issue or feel free to close it if they solve it.
Thanks!

**Comment by esuess** [comment]
Here is a news post about 5 million test that were distributed to the schools in Austria recently.  This may be the reason for the increased number of tests.

https://www.reuters.com/article/us-health-coronavirus-austria/austria-to-roll-out-5-million-coronavirus-tests-for-school-pupils-idUSKBN29E0HL
