### ISSUE TITLE
Vaccine data are all zero in US for all counties

### ISSUE THREAD

**Issue by longwenlixue** [covid19datahub/COVID19#149]
Hi Emanuele:

I can't see vaccine data each day for counties in US, all data are zero.

Will you update it in the future?

Thanks for your work

**Comment by esuess** [comment]
Hello @longwenlixue thank you for the suggestion.  We are working on adding data for US counties.  The planned data source will be  https://ourworldindata.org/us-states-vaccinations

**Comment by eguidotti** [comment]
Hi @longwenlixue, thanks for pointing this out. I implemented the source suggested by @esuess.
The data should be there in a couple of hours!
