### ISSUE TITLE
Problem getting Brazil's states and municipalities

### ISSUE THREAD

**Issue by murillorb** [covid19datahub/COVID19#151]
Good day, I tried to retrieve data from Brazil's municipalities and only cities from the state of ESPIRITO SANTO appear. I'd like to have data from all brazilian cities.

Command:  corona <- COVID19::covid19(country = "Brazil", level  =3)

**Comment by eguidotti** [comment]
Hi @murillorb, we would also like to have data from all brazilian cities. 
Can you suggest the official data provider for that? We would be happy to add those data in the hub.
Thanks!

**Comment by murillorb** [comment]
I was able to find this database. It does not have all data you have; for example, there is no policy information and the number of tests is computed only statewise.

https://github.com/wcota/covid19br/

**Comment by murillorb** [comment]
I have found a complete reference of vaccinations city-wise here: https://opendatasus.saude.gov.br/dataset/covid-19-vacinacao

**Comment by eguidotti** [comment]
Work in progress... almost done :) Stay tuned!

**Comment by eguidotti** [comment]
The full data for Brazil are now implemented. Let me know if you think something is still missing or find any inconsistency. Otherwise I'm going to close the issue.
Thanks!

**Comment by murillorb** [comment]
Thank you very much! Just a small issue: the state of Espírito Santo shows all caps, in contrast to all other states.

**Comment by eguidotti** [comment]
Thanks, this shoud be fixed in the latest commit
