### ISSUE TITLE
Covid Tracking Project ending

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#152]
How or will the wind-down of the Covid Tracking Project affect US data? https://covidtracking.com/analysis-updates/covid-tracking-project-end-march-7

I'm looking for alternative workflows that are currently reliant on the Covid Tracking Project, and already have several built around Covid19 Data Hub, so am wondering if I should refactor to here, or build from a different source entirely. Thx.

**Comment by eguidotti** [comment]
Hi @hlcny. I've changed the data providers to replace the covid tracking project. In particular:

> State-level data for US have changed data provider(s) due to the shutdown of the [COVID Tracking Project](https://covidtracking.com/analysis-updates/covid-tracking-project-end-march-7). Tests are now from the [Department of Health & Human Services](https://healthdata.gov/dataset/covid-19-diagnostic-laboratory-testing-pcr-testing-time-series). Hospitalized and ICU are now from [Department of Health & Human Services](https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state). Confirmed cases and fatalities are now from [The New York Times](https://github.com/nytimes/covid-19-data). Data at national and county level have not been affected.

Hope this helps! Feel free to re-open this issue if needed.
