### ISSUE TITLE
encoding for names in administrative_area_level_3

### ISSUE THREAD

**Issue by natalfa** [covid19datahub/COVID19#154]
Names in administrative_area_level_3 seem not to respond to UTF-8 or other encodings (e.g. returning string: Cesk<U+00FD> Krumlov). The issue is both in R download or direct .csv download of raw and processed data.
The issue was not present in downloads in December 2020.

**Comment by eguidotti** [comment]
Hi @natalfa, thanks for spotting this.
It should be fixed in a few hours

**Comment by natalfa** [comment]
Fantastic!
Grazie
