### ISSUE TITLE
Andalucia Spain is not updating

### ISSUE THREAD

**Issue by zoomio2** [covid19datahub/COVID19#155]
Last update is 25 January, 2021

**Comment by eguidotti** [comment]
Hi @zoomio2, thanks for your message.
This should be fixed in a couple of hours. They changed the link they are maintaining.
The data are from https://cnecovid.isciii.es/covid19/ 
Please let me know if there is a more comprehensive data source we can use.
Thanks!

**Comment by zoomio2** [comment]
Thank you! 
This site also has a lot of data from Spain: http://www.juntadeandalucia.es/institutodeestadisticaycartografia/salud/COVID19.html
