### ISSUE TITLE
Issue with data in Canada

### ISSUE THREAD

**Issue by EricDugas** [covid19datahub/COVID19#156]
Hi, 
I saw some issue with Canada data, specifically in level two , with Quebec data I saw that since February 1st, Canada changed their metrics. Maybe have a check with other provinces too. 

The tests column seems to have a mapping issue ... 
Hope there is enough information to understand the issue. 

I think your source data is from :  https://health-infobase.canada.ca/covid-19/
"Starting February 1, 2021, laboratory test indicators are based on the number of laboratory tests performed and the percentage of tests positive. These data replace previous metrics based on unique individuals tested and provide a more accurate measure of test positivity and promote greater standardization in reporting across Canada. The proportion of tests positive is expected to decrease compared with previous person-based methods, as all tests will be included in the calculation, including new tests on the same person over time."

![image](https://user-images.githubusercontent.com/77283931/109684707-8a20c100-7b4e-11eb-8623-190ab15faef3.png)

![image](https://user-images.githubusercontent.com/77283931/109685371-31055d00-7b4f-11eb-8cf4-9f0ad3bf35bb.png)

Regards,
Eric

**Comment by eguidotti** [comment]
Hi @EricDugas, thanks for your message.
It seems you are using the preprocessed data. If you use the raw data you should get missing data for the missing tests as in the original source. I think I'll merge the new way to count the tests with the old one, but users will see a spike as reported in the official source. What do you think?

PS: Please make sure to switch to the raw data as described in the breaking changes in the [README](https://github.com/covid19datahub/COVID19).

**Comment by EricDugas** [comment]
Hi @eguidotti 
I agree with you to merge the data. It will create a spike but it will reflect the true cumulative data. 

If you merge the two columns pay attention to January 31st 2021 as the data in column "numtested" is 2.7M and in column "numtests" is 5.5M on the same line. these two should not be sum. I don't know if you can create a logic like if column numtested is empty take numtests and the other way too.

**Comment by eguidotti** [comment]
Fixed. The update is reported in the [changelog](https://covid19datahub.io/news/index.html)
Thanks!
