### ISSUE TITLE
US Level 2 data with 0 observations 

### ISSUE THREAD

**Issue by uqzwang** [covid19datahub/COVID19#159]
It worked fine yesterday. Today, it return zero observations. Level 1 and Level 3 still work. 

`covid19(country = "US", level = 2)`
`# A tibble: 0 x 38`
`# Groups:   id [0]`

**Comment by eguidotti** [comment]
Thanks @uqzwang!
It seems they changed the link to the dataset for hospitalizations: https://healthdata.gov/dataset/covid-19-estimated-patient-impact-and-hospital-capacity-state

I disabled this for now and hope to find the new location of these data soon. In the meantime the other data should be back in a few hours.

**Comment by uqzwang** [comment]
Thank you. This package is very helpful! It works now for the data I needed as I do not analyze hospitalizations at the moment.
