### ISSUE TITLE
No recovered for USA and UK

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#161]
Dear Emanuele,
The data for recovered cases is missing in the US and the UK (Level 1). Could this be remedied? It makes it impossible to calculate current active cases.
Yours sincerely

**Comment by eguidotti** [comment]
Hi @guenterhack, thanks for your message. Unfortunately I think we never had the data about recovered cases for US and UK (level 1). Do you know when the timeseries of these data are available? I would be happy to add them.
Thanks!

**Comment by eguidotti** [comment]
This has been inactive for a while. Feel free to reopen, thanks!
