### ISSUE TITLE
About daily cases

### ISSUE THREAD

**Issue by VLucet** [covid19datahub/COVID19#163]
Hi, great package! I just meant to ask whether or not it is possible to get daily cases from the cumulative cases dataset. Is it appropriate to simply substract the value from the previous day or is there something I am missing here? 
Thanks!

**Comment by eguidotti** [comment]
Hi @VLucet , thanks for your feedback!
Yes, that's definitely the way but make sure to use the `raw` data. We avoid including daily numbers as they can be easily obtained by taking the differences from cumulative counts. In some cases, you may obtain negative daily numbers. There is not much we can do about that as sometimes the official providers provide decreasing cumulative counts. That's a known issue unfortunately.

**Comment by VLucet** [comment]
Thanks for your response, I can confirm I do get negative counts from times to times. 
Thanks for confirming.
