### ISSUE TITLE
province-level data for Mexico, Pakistan, Ukraine?

### ISSUE THREAD

**Issue by greg-minshall** [covid19datahub/COVID19#166]
hi.  the JHU data has province-level data for Mexico, Pakistan, and Ukraine.  i don't see them in  `rawdata-2.csv`.  am i looking the wrong place?  (if you need them, ... :)

**Comment by eguidotti** [comment]
You were looking in the very right place :) Fixed, the data are now available, thanks! 
Don't hesitate to let me know if you find something else.
