### ISSUE TITLE
Update data 

### ISSUE THREAD

**Issue by susanapsilva** [covid19datahub/COVID19#168]
I dont know if its just me but for updating data I need to install again the package. Otherwise I get last downloaded data. 
I'm using R 4.0.2 in Rstudio 1.3.1073.
Thanks a lot for working on gathering all this data.

**Comment by eguidotti** [comment]
Please have a look at the `cache` argument and set it to `FALSE` for long running programs. 
Hope this helps!

**Comment by susanapsilva** [comment]
It worked, thanks a lot.
