### ISSUE TITLE
Large database size

### ISSUE THREAD

**Issue by dherrera1911** [covid19datahub/COVID19#172]
I'm finding trouble using the package now because the data doesn't fit in my memory, despite that I only want a subset. The download works fine when I download data using level=1, but if I want the data from NYC, for example, I have to use `covid19(country="USA", level=3)` which makes me run out of my 8GB of memory, even if I provide a short time interval in start/end date.

**Comment by eguidotti** [comment]
Can you try to set the argument `cache = FALSE`? This should save same space in memory. 

It would be nice to ship the data in a sqlite database. This would be more efficient but will take some time before having it up and running

**Comment by dherrera1911** [comment]
Thanks for the quick response! I tried the `cache = FALSE` and it still crashed my memory. I'll just try to increase my swap or look for that specific data elsewhere (I'm still using the package for non level 3 locations).

Best

**Comment by eguidotti** [comment]
It's strange. The data file is below 1 GB. Are you using the package on CRAN? 

```r
install.packages("COVID19")
library(COVID19)
x <- covid19("USA", level = 3, cache = FALSE)
```
Another option you can try is to read directly the data file. 
```r
x <- read.csv("https://storage.covid19datahub.io/rawdata-3.csv")
```

Otherwise you can manually download the data [here](https://covid19datahub.io/articles/data.html)

**Comment by dherrera1911** [comment]
Yes, just using that fills my memory (I'm noticing it's partly filled, so maybe it's just 4 GB, but still). Thanks for the suggestions though!
