### ISSUE TITLE
USA level 3 data

### ISSUE THREAD

**Issue by xinleideng** [covid19datahub/COVID19#173]
Thanks for this great project!!
I found the population at level 3 for the USA was different from other resources like the American community survey. I found the data source is from world bank open data. Could you please help me to find the original data from the world bank open data or how do you estimate the population at level 3. 
Thank you so much!!!!

**Comment by eguidotti** [comment]
Hi @xinleideng, thanks for your message!
I have just fixed the data source for US population level 3. It is actually from JHU data: [this file](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv).

**Comment by xinleideng** [comment]
Hi @eguidotti, thank you so much for the quick reply! I got it. Thanks for your great work and effort!
