### ISSUE TITLE
Dataset isn't working like it used to for United Kingdom

### ISSUE THREAD

**Issue by LLanero077** [covid19datahub/COVID19#176]
Hi, I have been using this dataset lately to make a prediction using prophet. Today when I went to try to clean up my code when running it no data showed up. Im using the data regarding the United Kingdom.i have tried other countries and It works fine. If someone could assist me that would be very appreciated

**Comment by eguidotti** [comment]
Hi @LLanero077, thanks for your message. Can you provide a link or some more information about which level you are using and which variables? Otherwise it would be pretty hard for me to help out

**Comment by LLanero077** [comment]
Ive tried running it now again And it is working. But thank you for the reply

**Comment by eguidotti** [comment]
If you are using level 3 data, I've noticed that the [UK API](https://coronavirus.data.gov.uk/) is experiencing some downtime lately.  But happy it works now!
