### ISSUE TITLE
No city level data for Italy after 2021-03-25

### ISSUE THREAD

**Issue by drs81** [covid19datahub/COVID19#178]
When I request city level data for Italy, the most recent date available seems to be 25 March 2021. I wondered if there might be a reason for this? I am using v. 2.3.2 which I believe is the current version of the package. 

test<-covid19(country = "Italy", level = 3,raw = FALSE)
range(test$date)
[1] "2020-01-01" "2021-03-25"
 
Thank you!

**Comment by eguidotti** [comment]
Hi @drs81, thanks for posting your message here!
We stopped providing the preprocessed data (`raw=FALSE`) on April 2021 as described [here](https://covid19datahub.io/articles/data.html). Please use `raw=TRUE` or just drop it as it is the default in v2.3.2. The following should work:
```r
test <- covid19(country = "Italy", level = 3)
range(test$date)
```
It may take some time as the data file is quite large to download.
Hope this helps!

**Comment by drs81** [comment]
Thanks very much Emanuele, that's very helpful!

**Comment by drs81** [comment]
Apologies Emanuele, I just noticed that I am now suddenly getting this error which I am confused about...
test <- covid19(country = "Italy", level = 3)
Error: $ operator is invalid for atomic vectors

(N.B. the function does appear to be working OK if I specify the level argument as either 1 or 2 though).

**Comment by eguidotti** [comment]
Hi @drs81, thanks for reporting this. 
I am not able to reproduce the issue. It seems to work fine also for level 3 at the moment. Maybe it was a temporary issue.
Would you be able to give it another try?

**Comment by drs81** [comment]
Thanks for the reply @eguidotti. 
Silly me...looks like it was just a matter of updating R :). Seems to be working fine now. 
Thankyou very much!
