### ISSUE TITLE
Level 2 dataset update lagging

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#186]
Hi, the level-2 dataset update is lagging a day behind lately. And the level-3 dataset is on time. This strikes me as strange. Wanted to let you know. Thank you for all of your continued work on this!

**Comment by eguidotti** [comment]
Fixed, the updates should be more timely now. Thanks!

**Comment by kenshermock** [comment]
And I just noticed that the Maryland counties in the level 2 dataset also report no new cases since December 5. If you want me to register a formal issue through Github, please let me know.   Ken

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Tuesday, December 14, 2021 at 15:52
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [covid19datahub/COVID19] Level 2 dataset update lagging (Issue #186)


      External Email - Use Caution





Fixed, the updates should be more timely now. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fissues%2F186%23issuecomment-993988779&data=04%7C01%7Cken%40jhmi.edu%7C0eefe9a431b8414f29cf08d9bf43a442%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119504913504%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b%2Bw81Zlws%2FUegBaWQ5QdEyPp%2BN2ZS4kE3DWIdeFnBXI%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB4MMYBUJTI6MDYKAJW7JT3UQ6VAXANCNFSM5J77DH5A&data=04%7C01%7Cken%40jhmi.edu%7C0eefe9a431b8414f29cf08d9bf43a442%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119504923493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9l2HhXEXS1YGeWUbapnGXWleNuzfTApKh7CZ7r3rjCY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cken%40jhmi.edu%7C0eefe9a431b8414f29cf08d9bf43a442%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119504923493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=H0%2BPHIoEkjqiSkCrUBXXJuNbgm5%2Bqo%2B%2B7EIAxeHuzOk%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cken%40jhmi.edu%7C0eefe9a431b8414f29cf08d9bf43a442%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751119504933485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AOFi8Lm%2FhX6uPPrBW3DAUFMFyihIxKmmkoALf2yJ9Dc%3D&reserved=0>.

**Comment by eguidotti** [comment]
Hi @kenshermock, thanks for reporting this. I can confirm everything is working fine on the data hub side, but the data seem not to be updated by The New York Times (the data source used). I just opened an issue at their github repository: https://github.com/nytimes/covid-19-data/issues/649

**Comment by kenshermock** [comment]
Yes, I also checked in with the NYTimes and apparently no data have been reported by Maryland since December 5. I’m working to find out why. Thanks, the data hub is working just fine now. Appreciate your hard work!  Ken

From: Emanuele Guidotti ***@***.***>
Reply-To: covid19datahub/COVID19 ***@***.***>
Date: Wednesday, December 15, 2021 at 04:48
To: covid19datahub/COVID19 ***@***.***>
Cc: ***@***.***" ***@***.***>, Mention ***@***.***>
Subject: Re: [covid19datahub/COVID19] Level 2 dataset update lagging (Issue #186)


      External Email - Use Caution





Hi @kenshermock<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenshermock&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Reqc30%2BHalcJ2wzpHGPibJinmLzBeSju4eMMbt7uWQ4%3D&reserved=0>, thanks for reporting this. I can confirm everything is working fine on the data hub side, but the data seem not to be updated by The New York Times (the data source used). I just opened an issue at their github repository: nytimes/covid-19-data#649<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnytimes%2Fcovid-19-data%2Fissues%2F649&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IjP5G7uez9uUCDldDwjXhvY1umHrIk2CzFjOQtm7%2B50%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcovid19datahub%2FCOVID19%2Fissues%2F186%23issuecomment-994586762&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4ySDoHc%2FAcxYpDrpKAWYaLGa%2FTmbWB0nfviDmFZEyl4%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB4MMYC7N6F4C3G4GVJVZ3TURBP5LANCNFSM5J77DH5A&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ttIV8V2RgdcVBMM7rMEc12JjzD%2BxqsSK63%2FiuInOg6c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rNoA7clUxJVAmHuafLnse7n0%2FJQgc132Lp2fN%2B808Ak%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cken%40jhmi.edu%7C106736b567f84447337708d9bfafff52%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637751584911764358%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lSNaBujOzOvcN5HmPg148hLg5SJGWQiXTRe47JpVWeE%3D&reserved=0>.
