### ISSUE TITLE
International/upper-national data

### ISSUE THREAD

**Issue by I-I-IT** [covid19datahub/COVID19#189]
I suggest adding  **new levels for areas not strictly in one country**. 
Here is my proposed nomenclature. 
It is divided into political designation and geographical areas.

Level 0: 
**World**

Level 1:
**Super-continent** ([wiki](https://en.wikipedia.org/wiki/Supercontinent)) or Multi-continent very large geographical area
Large _**M**ulti-_**C**ontinent political aggregation

Level 2:
**Continent** or M-C medium-to-small geographical areas.
Small M-C political aggregation or continental political aggregation

Level 3:
**Anything under that** (uni-continent Geo areas and smaller than continental political aggregations)

 
Examples for easier understanding:
  Level 1 : Eurasia; G20; South; North
  Level 2: Asia,Europe,..; G7; EU; Middle East (3-continental)
  Level 3 : British Isles, Caribbeans, 

Note:
 Two main point of discussion
    How we cut Geo areas will need to be decided: do we select countries in them or do we take sub-nation areas into them ?
    Common definition for areas will need to be defined, perhaps by a wiki or something
 
 For technical side seems feasible although it's probably going to be in another category 
****

**Comment by eguidotti** [comment]
Hi @TechFanTheo and thanks for your message.
I'm not sure I understand correctly. Let me explain below.

The subdivions are dictated by the data sources (e.g., national ministry of health). They typically provide the data at 3 levels:

- national (country)
- sub-national (regions/states/cantons)
- lower-level (city/municipality/counties)

So we are using levels 1, 2, 3 to mimic the original providers. (For instance, there is no provider for Europe as a whole)

In the current version of the data hub, you can also find `key_gadm`, which is the identifier of the administrative area used in the [GADM](https://gadm.org/) database. This should serve to map the areas in standardized administrative levels. Is this what you are looking for?

A user may agrgegate the data to produce a dataset at the continent level, or at other standardized administrative area levels via GADM. However, aggregating the data is always quite dangerous (for instance, if we miss one European country, the counts for Europe would be understated). This is why we provide counts that are directly provided by the official sources (but without aggregating or manipulating them). In this sense, we are very much constrained to use the administrative subdivisions used by the original provider.

May it be useful adding such info to the README?

**Comment by I-I-IT** [comment]
I see, I believe it would be useful to have such classification bur
understand you don’t want to get into that. Also kinda a choice whether
stay an aggregator or become more of a analyser like OWID. Yes I believe
explaining it might be useful just to clarify.

(By the way I was looking to projects that use the data you are providing
and a few weeks ago I was on a GitHub page that listed them but can’t find
it. Do you know where it is ? I know I can download it but tbh a bit lazy
to learn R, etc right now)

**Comment by eguidotti** [comment]
OK, I'll update the README.
 
[Here](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=1585537563493742217) you can find the academic publications that use our data. But I'm now aware of the github page you are referring to. If you find it, please let me know. I'd be happy to have a look at it!

Thanks!

**Comment by I-I-IT** [comment]
Sorry I didn't  realise that the Covid19 Data Hub and the COVID-19 Open-Data- ([GitHub](https://github.com/GoogleCloudPlatform/covid-19-open-data) now sponsored by Google but previously independent ([old GitHub page when it was not Googled](https://github.com/open-covid-19/data))- were not the same. I seriously wonder what are the differences tough. The list I was talking about was not for this dataset sorry.

**Comment by eguidotti** [comment]
Thanks, I've updated the README. 

I am aware of that repo. Frankly, I was also wondering what was the difference the first time I discovered that. It would have been nice to join forces... Now it seems to me that we are providing a few data that they don't have and vice-versa. One can consider merging them to complement to two datasets. Cheers

**Comment by I-I-IT** [comment]
It seems that they have an additional level but I must say that I haven't
really managed to use either dataset yet. Anyway I think I can close the
issue now.
