### ISSUE TITLE
Should google place categories be present in all countries?

### ISSUE THREAD

**Issue by umbe1987** [covid19datahub/COVID19#190]
First of all, many thanks for this neat repository :pray: :pray: :pray:

I just noticed that [place categories](https://www.google.com/covid19/mobility/data_documentation.html?hl=en) are not present in some countries (e.g. Germany, Ireland).

```
# import mobility data from google
google <-
  covid19(
    gmr = TRUE,
    country = "Germany",
    level = 3,
    start = "2020-01-01",
    end = Sys.Date(),
    # current date
    dir = "data"
  )

# convert to data table (w/o copy)
setDT(google)

google_place_categories <- c(
  "retail_and_recreation_percent_change_from_baseline",
  "grocery_and_pharmacy_percent_change_from_baseline",
  "parks_percent_change_from_baseline",
  "transit_stations_percent_change_from_baseline",
  "workplaces_percent_change_from_baseline",
  "residential_percent_change_from_baseline"
)

google_place_categories %in% colnames(google)
```
The above code results in:
```
FALSE FALSE FALSE FALSE FALSE FALSE
```
Is this to be expected? Because they are for many other countries (e.g. Italy, Spain, France).

Thank you!

**Comment by eguidotti** [comment]
Hi @umbe1987, I just double checked but Google doesn't seem to provide mobility data for Germany at level 3 :( 
However, `level = 2` should work also for Germany and Ireland. If such data will be made available, I'd be happy to add them!

**Comment by umbe1987** [comment]
Thank you for your super quick response :wink:.

Hopefully they will make them available anytime soon...

Thank you again for this repo!

**Comment by umbe1987** [comment]
Ah, I don't know if it makes much sense, but maybe adding the columns with no data inside would be reasonable, in order to always obtain the same data structure (same column names). But feel free to ignore this comment ;)
