### ISSUE TITLE
Number of hospitalized patients for Australia is a floating point number

### ISSUE THREAD

**Issue by MinerMax555** [covid19datahub/COVID19#193]
For some dates (example: 2021-01-01) the number of hospitalized people in Australia is a floating point number (20.44 on 2021-01-01), which broke my import. Could you check that or give me an explanation what this floating point number means?

**Comment by eguidotti** [comment]
Thanks @MinerMax555! I notified the data curator for Australia to better understand this issue

**Comment by M3IT** [comment]
This was due to limitations of some data sources requiring calculations and has been fixed by rounding to the nearest integer.
For more info, see https://github.com/M3IT/COVID-19_Data/issues/9

**Comment by eguidotti** [comment]
@MinerMax555 and @M3IT 

Thanks both for your help! I confirm this is fixed now.
