### ISSUE TITLE
google tracking

### ISSUE THREAD

**Issue by LuiNov** [covid19datahub/COVID19#195]
Hello, I didn't get how to access the google data. Is there a guideline somewhere or could anybody explain it to me? 

Best wishes, 
Luise

**Comment by eguidotti** [comment]
Hi @LuiNov, please have a look here 

- https://covid19datahub.io/articles/r.html#google-mobility-reports

The following should work (in R):
```R
library("COVID19")
x <- covid19(gmr = TRUE)
```
Hope this helps!

**Comment by LuiNov** [comment]
🥰thanks! The package is really really great!!

**Comment by eguidotti** [comment]
Happy to hear that! 👍 
And thanks for your comment [here](https://github.com/covid19datahub/COVID19/issues/179#issuecomment-1023137095). I'll have a look at it later. 
I'm closing this issue as it seems it is fixed now. 
Cheers
