### ISSUE TITLE
Confirmed Cases China

### ISSUE THREAD

**Issue by wayne05de** [covid19datahub/COVID19#197]
Hello, there is a peak in China data in June 2021 (about 600 new cases) that i can not verify with other data sources.

**Comment by eguidotti** [comment]
Hi @wayne05de, thanks for your message. 

On `2021-06-04` I see 609 new cases for China. The data are from the [World Health Organization](https://covid19.who.int/) as documented [here](https://covid19datahub.io/reference/CHN.html). This is the link to the original data file where the data are pulled from:

- https://covid19.who.int/WHO-COVID-19-global-data.csv

Which data sources are you comparing with?

**Comment by wayne05de** [comment]
Hi @eguidotti,

thanks for your reply. I've compared WTO data (picture 1) with data from Johns Hopkins (picture 2):
![grafik](https://user-images.githubusercontent.com/78928756/151961822-172707c2-8bae-48ac-80ac-e5e3a6422e0d.png)

![grafik](https://user-images.githubusercontent.com/78928756/151961911-bd4e3eaf-e0ca-4752-956d-ce9b7eced9ea.png)

I calculated the new daily cases as an 7 day moving average. But in comparison there is a big difference in middle of 2021.

Best regards

**Comment by eguidotti** [comment]
Mmm... from this site it seems that Johns Hopkins is correct: 

- http://weekly.chinacdc.cn/news/TrackingtheEpidemic2021.htm

but WHO is definitely reporting different data:

- https://covid19.who.int/region/wpro/country/cn 

I just sent an email to them. Hope to get an answer!

**Comment by eguidotti** [comment]
Sadly, no reply so far...

**Comment by eguidotti** [comment]
It seems JHU removed Chinese data at the national level and split them into sub-regional data. So I'm keeping WHO for China level 1, and will implemenet China level 2 from JHU
