### ISSUE TITLE
Delayed Data Update

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#199]
Levels 2 and 3 have not updated since February 14. Thank you for your continued work.

**Comment by eguidotti** [comment]
Thanks as always for posting the issue!
I can see that the pipeline is working fine, but very (!) slowly. The last update is taking more than 13 hours to complete... 
This is probably a temporary issue, but let me investigate it further. I'd like at least to reduce the likelihood that it happens again in the future

**Comment by eguidotti** [comment]
It is fixed now. I added a small fix to restart the workflow in case it takes too long. Let's see if that works!
