### ISSUE TITLE
Can we add population density?

### ISSUE THREAD

**Issue by mikolajadamowicz** [covid19datahub/COVID19#200]
Population density will help us compare countries with similar vaccinated levels but different lifestyles/cultures. We can check how isolating works vs vaccinating for example. I can make a PR in couple of days if you give me a green light

**Comment by eguidotti** [comment]
Hi @mikolajadamowicz, thanks for your suggestion.

Actually, you can already import the population density (at the country level) in R:
```R
library(COVID19)
x <- covid19(wb = c("pop_density" = "EN.POP.DNST"))
```
In the snippet, the code `EN.POP.DNST` refers to the indicator available at https://data.worldbank.org/indicator/EN.POP.DNST Yes, this means you can already use all indicators at World Bank!

Including the population density at lower levels (i.e. 2 and 3) is a huge work. We'd need to manually insert them for more than 12.000 locations. Another option is to use some geospatial technique to compute the area of the locations using GADM shapefiles. But I'm not sure it is very useful as a user could do it him/herself if interested 

What do you think?

**Comment by eguidotti** [comment]
I assume this is OK
