### ISSUE TITLE
France, Israel - cases not updating

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#201]
Hi,
I've noticed that new case figures for France and Israel are not up-to-date. 
Best,

**Comment by eguidotti** [comment]
Hi @hlcny, thanks!

Sadly, the national provider for France has stopped updating the total counts. 

> En raison d’un allongement du délai de consolidation des données, la publication du nombre total de cas confirmés depuis le début de l’épidémie `conf` est temporairement arrêté à la date du 16/12/2021. Le chiffre quotidien de nouveaux cas confirmés reste quant à lui disponible.

- https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/#_

So, I have checked the agreement of these data with JHU (below). As they match quite closely and JHU is continuing to update the data, I have switched the provider to JHU for France.

Regarding Israel (and other countries!), there is indeed a bug that I should have fixed. Hopefully, the data should be up-to-date in a few hours!

![jhufra](https://user-images.githubusercontent.com/24247667/156224841-901ee0ab-d16c-4153-83cf-3030850d41bd.png)
