### ISSUE TITLE
Daily number of cases and of deaths in Portugal are avaiable again in

### ISSUE THREAD

**Issue by eguidotti** [covid19datahub/COVID19#205]
Daily number of cases and of deaths in Portugal are avaiable again in 
https://covid19.min-saude.pt/numero-de-novos-casos-e-obitos-por-dia 
Variables:
confirmation_date1 -> date
day_cum_abs_num ->cases
day_ob_abs_num -> deaths

_Originally posted by @susanapsilva in https://github.com/covid19datahub/COVID19/issues/179#issuecomment-1082461910_

**Comment by eguidotti** [comment]
Thanks @susanapsilva for reporting this. I'm getting the following message right now:

> Caro utilizador
O serviço encontra-se com muita procura.
Por favor volte a tentar dentro alguns minutos.
Muito obrigado.

I'll try again later

**Comment by susanapsilva** [comment]
You can try directly but I'm not surre if they will keep the same name structure over time. Here goes the link for most recent file:
https://covid19.min-saude.pt/wp-content/uploads/2022/03/covid_dados_2022-03-31_xlsx-36kb.xlsx

**Comment by eguidotti** [comment]
I always get the same error message... it doesn't seem to be working

**Comment by susanapsilva** [comment]
I don't understand why because the link works for me [https://covid19.min-saude.pt/numero-de-novos-casos-e-obitos-por-dia] in chrome and edge at least as you can see in the screenshot
![Screenshot 2022-05-11 21 40 29](https://user-images.githubusercontent.com/52658492/167944090-3d13ba5c-0091-4a0c-9ae9-eba9dc5d30e3.png)
Thanks

**Comment by eguidotti** [comment]
Hi @susanapsilva, I tried several times again from Safari and Chrome. Sadly, I'm still getting the same error message:

<img width="1189" alt="Screenshot 2022-06-02 at 10 30 24" src="https://user-images.githubusercontent.com/24247667/171588944-2d4733e8-c771-4e54-89d3-fd362f16503d.png">

It seems it is the base domain that is not working for me: https://covid19.min-saude.pt Maybe they are restricting access outside of Portugal (it would not make much sense though)

**Comment by susanapsilva** [comment]
It doesn't make sense, but it might be exactly that :(

**Comment by susanapsilva** [comment]
Hi @eguidotti 

At the github project you used for Portugal you can now find daily data too.
https://github.com/dssg-pt/covid19pt-data/blob/master/dados_diarios.csv

Variables:

data -> date
confirmados -> confirmed 
confirmados_novos ->new cases
obitos -> deaths
obitos_novos -> new deaths

Thanks
