### ISSUE TITLE
The script needs to be updated for the Brazil's Level 3

### ISSUE THREAD

**Issue by felipemfp** [covid19datahub/COVID19#206]
The source [wcota/covid19br](https://github.com/wcota/covid19br) is now splitting the level-3 data by year.

The data for previous years are available at `cases-brazil-cities-time_20xx.csv.gz` files, while the data for the current year are at `cases-brazil-cities-time.csv.gz`. 

They have an example of how to collect the data using Python and Pandas: 

```python
pd.concat([pd.read_csv(x) for x in glob.glob('cases-brazil-cities-time_2*.csv.gz') + ['cases-brazil-cities-time.csv.gz']])
```

**Comment by eguidotti** [comment]
Thank you!!! Commit 1d5d1f423da5fc4d252f403d2f3996ba0b047e44 should fix that. Let's wait a couple of hours to check whether it works as intended

**Comment by eguidotti** [comment]
It seems to be fixed

**Comment by felipemfp** [comment]
Thank you!
