### ISSUE TITLE
No level 3 data for U.S. after May 13, 2022

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#207]
Hi, I noticed today that there are no data posting in the level 3 data for the U.S. (i.e., county-level) after May 13. This is true for all counties. Previously, I had downloaded data up to May 17 so something has changed. Thanks, as always, for your hard and determined work on this project.

**Comment by eguidotti** [comment]
Hi @kenshermock, thanks for your message! I found that the [New York Times](https://github.com/nytimes/covid-19-data) has split the data for counties in different files and the main data file is no longer supported:

> UPDATE: County-level data for cases and deaths is now available in separate files for each year: [us-counties-2020.csv](https://github.com/nytimes/covid-19-data/blob/master/us-counties-2020.csv), [us-counties-2021.csv](https://github.com/nytimes/covid-19-data/blob/master/us-counties-2021.csv) and [us-counties-2022.csv](https://github.com/nytimes/covid-19-data/blob/master/us-counties-2022.csv). The existing [us-counties.csv](https://github.com/nytimes/covid-19-data/blob/master/us-counties.csv) file will no longer be updated once it reaches the Github file size limit of 100MB.

My last commit should have fixed this issue. It will take a couple of hours for the new data to be available and to confirm everything is working as it should. Thanks again for your continued support!
