### ISSUE TITLE
CZE google mobility indicators are NA in Prague (key_nuts = "CZ010")

### ISSUE THREAD

**Issue by umbe1987** [covid19datahub/COVID19#208]
It seems google mobility indicators for Prague are all NA even if they are present in google mobility report CSV.

The code I am using is:

```
library(data.table)
test <- covid19(gmr = T, country = "Czech Republic", level = 3, start = "2020-01-01", end = Sys.Date())
setDT(test)
google_indicators <- c(
  "retail_and_recreation_percent_change_from_baseline",
  "grocery_and_pharmacy_percent_change_from_baseline",
  "parks_percent_change_from_baseline",
  "transit_stations_percent_change_from_baseline",
  "workplaces_percent_change_from_baseline",
  "residential_percent_change_from_baseline"
)
test[key_nuts == "CZ010", ..google_indicators, ]
```
The result is all NA even if in the downloaded file (`2020_CZ_Region_Mobility_Report.csv`) the values are present.

Is it a problem related to how the join is made?

**Comment by eguidotti** [comment]
Hi @umbe1987, thanks for your message! 

> It seems google mobility indicators for Prague are all NA even if they are present in google mobility report CSV.

It seems to me that the google indicators for Prague are for level 2 (`place_id = ChIJi3lwCZyTC0cRIKgUZg-vAAE`). If you try the following, you should get the Google reports for Prague:
```R
test <- covid19(gmr = T, country = "Czech Republic", level = 2, start = "2020-01-01", end = Sys.Date())
```

At level 3 (districts) it seems that Prague is subdivided into East and West district by Google. However, the cases are not subdivided into East and West for level 3. So I left this match blank. But maybe I should use the same `place_id = ChIJi3lwCZyTC0cRIKgUZg-vAAE` also for Prague at level 3 as the cases are actually the same for Prague at the two levels... what do you think?

**Comment by umbe1987** [comment]
Hello @eguidotti and thanks for you feedback.

IMO it would make sense for CZE, as Prague seems the only area missing from the join and it is "an important area".
I am not totally aware on the way cases and google reports are merged together, but if `place_id = ChIJi3lwCZyTC0cRIKgUZg-vAAE` can be used when asking for `level = 3` I think this would be a useful change.

**Comment by eguidotti** [comment]
Sorry, I fogot to update this thread but the issue was fixed already last week. Thanks!

**Comment by umbe1987** [comment]
> Sorry, I fogot to update this thread but the issue was fixed already last week. Thanks!

This is great news! Thank you @eguidotti! :+1:
