### ISSUE TITLE
France - Missing deaths data before Feb 05, 2021

### ISSUE THREAD

**Issue by felipemfp** [covid19datahub/COVID19#209]
For some reason, I'm not seeing the number of deaths for the days before Feb 05, 2021, for France.

**Comment by eguidotti** [comment]
Thank you! The data are missing from the official provider: https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/#_ It seems they have removed the column `dc_tot` (cumulation of deaths recorded in hospital and in EMS) before Feb 05, 2021.

I wonder whether we should switch to another source for this metric
