### ISSUE TITLE
Data updates

### ISSUE THREAD

**Issue by pmaier1971** [covid19datahub/COVID19#211]
Data for Canada, Italy, UK and Japan no longer updated

**Comment by eguidotti** [comment]
Italy is fixed. 

Canada switched from daily to weekly frequency. This should be visible in the next release of the data (a few hours from now)

UK has stopped reporting the data in May 2022.
https://coronavirus.data.gov.uk/details/cases?areaType=overview&areaName=United%20Kingdom
The data are still updated for lower levels: England, Northern Ireland,  Scotland, Wales. I'm checking whether to switch to another source for UK as a whole

The source for Japan stopped updating the data. But the data are still updated by other sources. I'm probably switching to https://toyokeizai.net/sp/visual/tko/covid19/en.html in the next few days

**Comment by lisphilar** [comment]
Regarding Japan data, https://toyokeizai.net/sp/visual/tko/covid19/en.html was closed.

I'm providing [a manually-updated dataset](https://github.com/lisphilar/covid19-sir/tree/main/data) using the following primary sources.
- https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_00086.html
- https://www.kantei.go.jp/jp/headline/kansensho/vaccine.html

It is difficult for me to update the dateset every day, but I hope this could be an alternative.

**Comment by eguidotti** [comment]
Thanks @lisphilar, it seem to be a great repository. However, I understand that updating the data manually can be very time consuming and the repo seems to have been last updated one month ago

**Comment by eguidotti** [comment]
Hi @lisphilar, I'm finally integrating your data! I've found an issue with the vaccination data and opened an issue at https://github.com/lisphilar/covid19-sir/issues/1373

**Comment by lisphilar** [comment]
I'm sorry for my late reply.
I will investigate the issue and update the database.

**Comment by eguidotti** [comment]
With https://github.com/covid19datahub/COVID19/commit/ec8865dfd854026dfff46d1e280a231c3190c02d I've integrated your data in the hub. They should become available in the next few hours. Thanks for your help @lisphilar !

**Comment by eguidotti** [comment]
I confirm the data have been successfully integrated
