### ISSUE TITLE
No "confirmed" data updates since 21/11/2022

### ISSUE THREAD

**Issue by PowershellNinja** [covid19datahub/COVID19#212]
For most countries in the dataset, the "confirmed" data values have not been updated since 21/11/2022 or even some days earlier.

Examples are:
94214817 - Azerbaijan , showing same "confirmed" numbers since 20/11/2022
5eda1083 - France, showing same "confirmed" numbers since 18/11/2022
59a13ceb - United States , showing same "confirmed" numbers since 20/11/2022

Have all these countries stopped reporting data or is maybe something wrong with the data load?

**Comment by eguidotti** [comment]
Sorry for the late response. I'm not able to reproduce this issue. It seems that the data are now up-to-date. Maybe that was a temporary issue?

**Comment by PowershellNinja** [comment]
I just verified, and the data is up to date again - was probably temporary. Thanks for the answer anyways :)
