### ISSUE TITLE
France series

### ISSUE THREAD

**Issue by malouche** [covid19datahub/COVID19#29]
How it comes that the number of confirmed cases in France in  2020-04-21  is 156921 and on the next days on 2020-04-22 decreases to 154715?

Thanks

**Comment by eguidotti** [comment]
Thanks for pointing this out! Those data come from [JHU CSSE](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv)

I'd suggest you open an issue there or you are welcome to [join us](https://github.com/covid19datahub/COVID19/blob/master/CONTRIBUTING.md) and help finding a better data source.

Thanks!
