### ISSUE TITLE
Unable to establish a connection to the server

### ISSUE THREAD

**Issue by JTCDCTWB** [covid19datahub/COVID19#34]
Warning message:
In file(con, "r") : InternetOpenUrl失败:’无法与服务器建立连接'

**Comment by eguidotti** [comment]
Please post your request in English and check to have an internet connection when using the package

**Comment by JTCDCTWB** [comment]
Error in file(file, "rt") : Unable to open the chain
 Warning message:
In file(file, "rt") :
  InternetOpenUrl Failure: unable to connect to the revocation server, or failed to get a final response. '

**Comment by eguidotti** [comment]
It seems you are offline. The package requires internet connection to work.
If this is not the case, please post your code and provide more information to make it easier to help. 
Thanks

**Comment by JTCDCTWB** [comment]
![微信截图_20200502203018](https://user-images.githubusercontent.com/64447691/80864212-d2175300-8cb3-11ea-91e2-95c4ae2b5a6c.png)
Thank you for your reply to my question！
Unable to connect while loading. Does my R need special Settings?

**Comment by eguidotti** [comment]
No special settings needed, just an internet connection.
Try to run `install.packages("COVID19")` and make sure you can open this page from your browser:
https://github.com/covid19datahub/COVID19/blob/master/DESCRIPTION

**Comment by JTCDCTWB** [comment]
My browser can open the page you provided.But my R cannot connect to the server.

**Comment by eguidotti** [comment]
I see, that's very strange. When loading, the package just tries to open the link I sent to check for updates. You should be able to use the package even if it fails, can you?

Also, try to install the latest version using this command:

```r
remotes::install_github('covid19datahub/COVID19')
```

Then try...
```r
require(COVID19)
sessionInfo()
```
... and copy here the output so I can try to help further. Thanks

**Comment by JTCDCTWB** [comment]
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] COVID19_1.2.2 remotes_2.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      rstudioapi_0.11   magrittr_1.5      tidyselect_1.0.0 
 [5] R6_2.4.1          rlang_0.4.5       fansi_0.4.1       dplyr_0.8.5      
 [9] tools_4.0.0       pkgbuild_1.0.7    cli_2.0.2         withr_2.2.0      
[13] ellipsis_0.3.0    assertthat_0.2.1  rprojroot_1.3-2   tibble_3.0.1     
[17] lifecycle_0.2.0   crayon_1.3.4      processx_3.4.2    purrr_0.3.4      
[21] callr_3.4.3       vctrs_0.2.4       ps_1.3.2          curl_4.3         
[25] glue_1.4.0        pillar_1.4.3      compiler_4.0.0    backports_1.1.6  
[29] prettyunits_1.1.1 pkgconfig_2.0.3  
 Thank you！

**Comment by eguidotti** [comment]
Yes the package is attached. Try to use that 
```r
require(COVID19)
x <- covid19()
```

**Comment by JTCDCTWB** [comment]
Sorry, I still can't connect to the server.After R is restarted, the package still cannot be loaded.
`> library(COVID19)
The coronavirus situation is changing fast. Checking for updates...
Warning message:
In file(con, "r") : InternetOpenUrl失败:’无法与服务器建立连接'`

**Comment by JTCDCTWB** [comment]
Your package should be all right.I guess it's my computer's Settings, like firewall Settings.I'll try to work it out for myself.I'll give you feedback if there is any result.
I am Chinese, please forgive my bad English.

**Comment by eguidotti** [comment]
I see, yes that's probably some specific settings. On the other hand, from your `sessionInfo` the package seems to be loaded correctly (despite the warning message you get). So I guess you could still try to run the `covid19()` function and see what happens.

Don't worry about the English, I'm Italian I speak bad English too :)

Let me know if you have any new result and feel free to join our community on [Slack](https://join.slack.com/t/covid19datahub/shared_invite/zt-dld2grt2-vmso7HkI8yFabW5R_mAZJw). I'm closing the issue in the meanwhile.
