### ISSUE TITLE
Having error while loading repository

### ISSUE THREAD

**Issue by vishakhagaikwad** [covid19datahub/COVID19#62]
# Install COVID19
> remotes::install_github("covid19datahub/COVID19")
Downloading GitHub repo covid19datahub/COVID19@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/covid19datahub/COVID19/tarball/master'
> 
> # Install COVID19
> remotes::install_github("covid19datahub/COVID19")
Downloading GitHub repo covid19datahub/COVID19@master
covid19datahub-COVID19-31935e9/man/figures/apple-touch-icon.png: truncated gzip input
tar.exe: Error exit delayed from previous errors.
Error: Failed to install 'COVID19' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\choti\AppData\Local\Temp\Rtmpg1s3Jr\file2bbc2489976.tar.gz" -C "C:/Users/choti/AppData/Local/Temp/Rtmpg1s3Jr/remotes2bbc5fc55a4b"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\choti\AppData\Local\Temp\Rtmpg1s3Jr\file2bbc2489976.tar.gz"' had status 1

**Comment by eguidotti** [comment]
Hello and thank you for reporting.
I cannot replicate the issue and the command seems to work fine on Windows. Are you using Mac or something else? Also, can you provide the R version you are running?
I'd suggest to try the following in the meanwhile:

- shut down Rstudio and restart
- make sure you have a working internet connection
- try again `remotes::install_github("covid19datahub/COVID19")`
- if not, try the following:

```R
install.packages("devtools")
devtools::install_github("covid19datahub/COVID19")
```

**Comment by vishakhagaikwad** [comment]
Sir currently I'm using R version 1.2.1335.....
Okay sir I'm following what u r mentioned step

**Comment by eguidotti** [comment]
That's the Rstudio version I guess. Your R version should be >= 3.5.0

**Comment by vishakhagaikwad** [comment]
Create a new ds_* file, named with the domain of the data source: eg ds_domain_com.
not getting this step

**Comment by eguidotti** [comment]
Ok thank you for the feedback, I slightly changed the tutorial. Is it more clear now?
https://github.com/covid19datahub/COVID19/wiki/Add-a-new-data-source
Thanks

**Comment by eguidotti** [comment]
Seems like it's no longer related to the package. Closing the issue
