### ISSUE TITLE
City and country names not showing up

### ISSUE THREAD

**Issue by s-schachterle** [covid19datahub/COVID19#64]
Hi - Thank you for all your work. This is a remarkable contribution!!!

I noticed that in early version of the R package, covid19, the city and state names were visible from the ID variable. Now it's outputting the underlying codes without the place names. Is that bug? If not, is there a crosswalk to link the codes with the place names?

> require("COVID19")
> 
> us.city <- covid19("USA", level = 3)
> us.city.list <- sort(unique(us.city$id))

> us.city.list[1:20]
 [1] "0007cb93" "00261c81" "004a8ee7" "0051e968" "006b65bd"
 [6] "00738b9f" "0083c472" "008b8a54" "00a1a685" "00b3d68a"
[11] "00b948a7" "00cc6d45" "00cebd4e" "00fc7fbd" "010cd779"
[16] "010e0772" "013e158a" "0141ae45" "0163ccb2" "0171bcbd"
>

**Comment by eguidotti** [comment]
Hi, thank you for your feedback!
The package went under heavy development in the last weeks and we are going to release a major update on CRAN today or tomorrow. Please try it out:
```r
remotes::install_github("covid19datahub/R")
```
The id is now a unique hash for each location, this is more stable than region/city names.
The corresponding country, state and city names have been moved in the `administrative_area_level_*` columns. Here the dataset documentation: 
https://covid19datahub.io/articles/doc/data.html

Hope this helps :)

**Comment by s-schachterle** [comment]
Thanks!!!!
