### ISSUE TITLE
Policy Measures in US States dont seem correct

### ISSUE THREAD

**Issue by jsilve24** [covid19datahub/COVID19#73]
Thanks for putting this package together!. 

Looking at Georgia I notice that all policy variables have increased over time without any decrease. Georgia has relaxed a number of restrictions and this relaxation does not seem to be accounted for. 

Could you please shine some light on this?

**Comment by eguidotti** [comment]
Thank you for pointing this out!
The data for policy measures are provided by [Oxford Covid-19 Government Response Tracker](https://github.com/OxCGRT/covid-policy-tracker). Would you mind opening an [issue](https://github.com/OxCGRT/covid-policy-tracker/issues) there to notify the inconsistency? Once they update, you will get the new data from the package. Hope this helps!

**Comment by jsilve24** [comment]
done

https://github.com/OxCGRT/covid-policy-tracker/issues/16

**Comment by jsilve24** [comment]
So I think it is actually an issue with this package. https://github.com/OxCGRT/covid-policy-tracker/issues/16 -> they said they only provide national data. Somehow this package is outputting state-level policy measures when it should probably be NA.

**Comment by eguidotti** [comment]
State-level policies are inherited from country-level policies. Please see #72 
I'm going to update the docs and make this point clear. Thanks!
