### ISSUE TITLE
Error in UK data on 01/06/2020

### ISSUE THREAD

**Issue by pbsis** [covid19datahub/COVID19#74]
The deaths data is incorrect for the UK between 24-May and 01-Jun. On 01-Jun, a historical correction of 445 was introduced to add deaths tested by commercial labs (called "pillar 2"). In the official government figures this correction was retrospectively applied to previous reporting dates from 24-May to 31-May. Your data has applied the entire 445 correction to 01-Jun, increasing the correct number that day of 111 to an artificially high 556. I assume this will have happened because you just take the latest announced cumulative total and so the detail of the correction was missed.

I suggest refreshing your UK data based on the official DHSC numbers available here:

- https://coronavirus.data.gov.uk/downloads/csv/coronavirus-deaths_latest.csv

That will result in the following updates to your UK cumulative deaths:

- 23-May: 36675 (Correct)
- 24-May: 36793 > 37116
- 25-May: 36914 > 37237
- 26-May: 37048 > 37373
- 27-May: 37460 > 37807
- 28-May: 37837 > 38220
- 29-May: 38161 > 38593
- 30-May: 38376 > 38819
- 31-May: 38489 > 38934
- 01-Jun: 39045 (Correct)
- 02-Jun: 39369 (Correct)
- 03-Jun: 39728 (Correct)
- 04-Jun: 39904 (Correct)

A similar correction was applied of ~4000 deaths on 29-Apr that your data does correctly incorporate in the same way as the UK government retrospectively applied it. Both corrections should have the same treatment.

Many thanks - happy to offer any additional clarification required.

**Comment by eguidotti** [comment]
Thank you @pbsis for your detailed comments.

>  I assume this will have happened because you just take the latest announced cumulative total and so the detail of the correction was missed.

This is not actually the case. We always connect to the latest data from the original data source, all changes are automatically reflected in our package. The point is that the data source for UK deaths was [JHU CSSE](https://github.com/CSSEGISandData/COVID-19). I switched the source to the better one you provided.

You should be able to get the correct data directly from the [package](https://cran.r-project.org/package=COVID19) in an hour or so. Let me know if this works.

Thanks!

**Comment by pbsis** [comment]
Fantastic - many thanks for the extremely quick turnaround - data looks perfect now.

I realised as soon as I saw your commit that I should have taken a better look around your repo first rather than making assumptions!
