### ISSUE TITLE
No data for China

### ISSUE THREAD

**Issue by JTCDCTWB** [covid19datahub/COVID19#75]
No Chinese data was available.

**Comment by eguidotti** [comment]
China is there for level 2.
Can you suggest a data provider for national level data?
Thanks

**Comment by JTCDCTWB** [comment]
I got the data from China.Thanks!
But,how can I  suggest a data provider for national level data?

**Comment by eguidotti** [comment]
Simply write here where you found the data :)
So we can have a look and implement in the package.
Thanks

**Comment by JTCDCTWB** [comment]
https://gitee.com/GuangchuangYu/nCov2019

**Comment by dshripadwaipune** [comment]
No data for China and Australia

**Comment by eguidotti** [comment]
Data for Australia have just been added in #77 
Data for China still have to be implemented. May you help with that?

**Comment by JTCDCTWB** [comment]
I'm sorry!But I'm not capable of finishing the work.

**Comment by klrosenbaum** [comment]
Hi, the file below has China data. I am not knowledgable enough of R to assist with the implementation, but I thought I would share this link, in case it is helpful. I too would appreciate access to China. Thank you. 

https://covid19.who.int/WHO-COVID-19-global-data.csv

**Comment by eguidotti** [comment]
Hi @klrosenbaum, many thanks for the link.
I added the data for China from WHO.
You should be able to access the data in a couple of hours.

**Comment by JTCDCTWB** [comment]
Thank you.
