### ISSUE TITLE
I cannot find data for Kansas City, MO

### ISSUE THREAD

**Issue by zngtian** [covid19datahub/COVID19#79]
Hello, 

I cannot find the rows for Kansas City, MO in the data of administrative level 3. Could you please help me point out where it is? How did you deal with Kansas City and the counties that the city overlaps? 

FYI. In the github repo of NYTimes, it says "Four counties (Cass, Clay, Jackson and Platte) overlap the municipality of Kansas City, Mo. The cases and deaths that we show for these four counties are only for the portions exclusive of Kansas City. Cases and deaths for Kansas City are reported as their own line."

Thanks.

Zheng

**Comment by eguidotti** [comment]
Hello, the data for US counties are from [JHU CSSE](https://github.com/CSSEGISandData/COVID-19) at the moment. You can refer to their documentation for Kansas City. Actually, [NYTimes](https://github.com/nytimes/covid-19-data) seems a better source for US data, we may consider switching to it.
What do you think?

**Comment by zngtian** [comment]
Thanks, Emanuele, for replying. 

Yes, NYTimes is a good, cleaner source for county and state level data. I have been using it since March. But it only has confirmed and death cases. It will be great if you can combine it with other data sources. I appreciate the comprehensiveness of your dataset. 

Best,
Zheng

**Comment by eguidotti** [comment]
Hello @zngtian, I changed the data provider from JHU CSSE to NYTimes for US data level 3.
You should be able to get Kansas City as well as the other counties from NYTimes in a couple of hours. Everything will be documented on the [website](https://covid19datahub.io/articles/data.html) very soon. 

The data providers for levels 1 and 2 seem already well documented and more comprehensive than NYTimes so they won't be changed. 

Please let me know if this works for you and/or if you have other ideas to improve the dataset. 

Best,
-- Emanuele
