### ISSUE TITLE
Add Information on Number of Tests

### ISSUE THREAD

**Issue by mschrein** [covid19datahub/COVID19#80]
Hello,
it would be great if the number of tests realised by country and date could be added. Such as available here [https://ourworldindata.org/coronavirus-testing](url)

Best

**Comment by eguidotti** [comment]
Sorry but I don't get your request. The number of tests by country is already included and the data are from the same source you are providing.
Am I missing something?

**Comment by mschrein** [comment]
Sorry I must have missed this. But perfect, then it is already implemented
