### ISSUE TITLE
US City Data, recent data missing, and NC County Missing

### ISSUE THREAD

**Issue by Ghotitox** [covid19datahub/COVID19#81]
1) City Level Data in the US is not current- latest date is June 12, 2020. 
2) For US, North Carolina, City data, "Alamance" (the first county alphabetically) is missing.  In reality, there are 100 counties in the state... even though there are 100 entities for Counties, one of them is "Out of NC"

Reproducible code below:
data3 <- subset(covid19("US", level=3),state=="North Carolina")
table(data3$city) #first county alphabetically is missing, should be "Alamance"
max(data3$date) #returns "2020-06-12"

**Comment by eguidotti** [comment]
Hi @Ghotitox, I'm afraid you are using a very old version of the package. There is no column `state` in the dataset and the reproducible code raises erros.

Please run `install.packages('COVID19')` and try again. 

US data level 3 are now from The New York Times as stated in the [changelog](https://covid19datahub.io/news/index.html).
Hope this helps

**Comment by eguidotti** [comment]
Closed for inactivity.
Feel free to reopen.
Thanks
