### ISSUE TITLE
missing populations

### ISSUE THREAD

**Issue by kradimer** [covid19datahub/COVID19#82]
Hi, I'm new and have much to learn.  First, thank you for making this very cool package!

Second, I am wondering why there is no population data for countries with id ERI, GPC and MSZ.  

Thank you again!

**Comment by eguidotti** [comment]
Hi @kradimer, welcome to the hub :)
ERI -> Eritrea
GPC -> Grand Princess (Cruise)
MSZ -> MS Zaandam (Cruise)
You can find the full list of id and population data (for level 1) [here](https://github.com/covid19datahub/COVID19/blob/master/inst/extdata/db/ISO.csv).

We didn't find the population data for Eritrea and the number of passengers for the ships. If you are able to find the data (maybe on wikipedia?) please type them here (together with the data source) and I can update the file. Then they will be automatically available via the package.

**Comment by kradimer** [comment]
Thank you!  You're right that Eritrea is a little tricky to find the population for.  Wikipedia has it at 5,750,433 with several sources noted, so that's probably a reasonable estimate (https://en.wikipedia.org/wiki/Demographics_of_Eritrea).

Wikipedia says that there were 3,533 people aboard the Grand Princess Cruise, counting staff and passengers (https://en.wikipedia.org/wiki/COVID-19_pandemic_on_Grand_Princess).

There were 1829 aboard the MS Zaandam (https://en.wikipedia.org/wiki/COVID-19_pandemic_on_cruise_ships#Zaandam_and_Rotterdam).

Thank you for your help!  I am using your excellent program for a grad school project. :)

**Comment by eguidotti** [comment]
Thank you for your feedback and data! Just added.
You should be able to get the new data directly from the package in a couple of hours.

Please make sure to use the CRAN version for your project:
`install.packages("COVID19")` 

Don't hesitate to join us on [Slack](https://join.slack.com/t/covid19datahub/shared_invite/zt-e921sryd-Sb97p~skvovQM6NuXFUNCw) and help further if you wish.

Best,
-- Emanuele
