### ISSUE TITLE
Mirai Solutions using covid19datahub

### ISSUE THREAD

**Issue by GuidoMaggio** [covid19datahub/COVID19#86]
Dear Emanuele

Following the CovidR contest and some problems we have had with the data we are currently using we have decided to switch to the Covid19datahub project for our dashboard.
https://mirai-solutions.ch/gallery/covid19/ 

On the top left we will replace the "Data Source" text with your info. A screenshot from the feature branch attached.
![image](https://user-images.githubusercontent.com/13679154/86330408-ef32b880-bc47-11ea-8a9a-60019ba8a3ac.png)

On the ReadMe file we have quoted yourself, David Ardia and again referenced your website.
https://github.com/miraisolutions/Covid19/pull/112

Let me know if this seems sufficient as a quote.
I believe we can go live on the master today.

We are also happy to be mentioned in your "usage" page!
https://covid19datahub.io/articles/usage.html 

I would like to thank you for the great project you have put in place and for all the extraordinary efforts you and your team have made (!!!) .

Best regards
 
Guido Maggio

**Comment by eguidotti** [comment]
Dear @GuidoMaggio,
thank you for your message and acknowledgments.

It is a pleasure to add your dashboard in our usage page, it will be live in a couple of hours.
I named it "Mirai Solutions Dashboard". If you have a specific title for your project, please let me know and I'll update.

Thank you!
--Emanuele

**Comment by GuidoMaggio** [comment]
Dear @emanuele-guidotti 

We do not have a specific name, it was actually just Covid19 like yours. 
"Mirai Solutions Dashboard" is perfect, thank you.

We just went live now with your data on master. If you believe we can do anything more to quote your project please let me know for the next release.

We would also be interested in knowing what your release plan on CRAN is. At the moment we are taking the COVID19 package from CRAN,

Thank you

Guido

**Comment by eguidotti** [comment]
Sure, we are hosting the development version for CRAN [here](https://github.com/covid19datahub/R). 
It should be released by the end of the month.

Don't hesitate to let me know how you think it can be improved.

Emanuele
