### ISSUE TITLE
CovsirPhy (Python package for COVID-19 analysis) will use COVID-19 Data Hub 

### ISSUE THREAD

**Issue by lisphilar** [covid19datahub/COVID19#87]
Dear @emanuele-guidotti  and COVID-19 Data Hub team,
Thank you for creating this dataset and Python interface.

We are developing python package to analyse COVID-19 data with SIR-like models (and open dataset for Japan).
CovsirPhy: https://github.com/lisphilar/covid19-sir

Currently, we are using different datasets for analysis (JHU dataset, OxCGRT dataset, population values). However, I'd like to switch to COVID-19 Data Hub and use Python interface `covid19dh` as a dependency of CovsirPhy in the next version.

I found comments on this package in your paper.
When we use `covid19dh` as a dependency to download the dataset, it is enough to cite the paper as follows?

Guidotti, E., Ardia, D., (2020). COVID-19 Data Hub, Working paper, https://www.researchgate.net/publication/340771808_COVID-19_Data_Hub

Should we show the citation lists (stdout of `covid19dh.covid19(country=None, verbose=True)`) when the users download this dataset?

I'm looking forward to collaborating with you!
Best Regards,
Lisphilar

**Comment by eguidotti** [comment]
Dear @lisphilar,
thank you for your message.

Yes, the citation of the working paper is fine (it will be hopefully published soon). It would be great if could also place the link to our [website](https://covid19datahub.io/) or repository somewhere in the description of your package to make it easier for others to find the data hub.

Regarding Japan, we should already have the data at prefecture level (from [here](https://github.com/swsoyee/2019-ncov-japan)) but please don't hesitate to tell me how you think it can be improved. 

For the citation list, I believe the user might be interested in knowing where the data are coming from. I would leave the argument `verbose=True` to let the user decide if to show the data sources or not. You might also want to consider exporting the citation function to have more information on the data providers, but it's up to you.

Thanks!
-- Emanuele

**Comment by eguidotti** [comment]
Btw, let me know if you'd like to showcase your project [here](https://covid19datahub.io/articles/usage.html) once it'ready :)

**Comment by lisphilar** [comment]
Dear @emanuele-guidotti ,
Thank you for your prompt reply!

In the next update, we will cite your (working) paper and website in documentation.
Please consider introducing my package as a use case. Description and URL could be:
CovsirPhy: Python package for COVID-19 analysis with SIR-derived ODE models
https://github.com/lisphilar/covid19-sir

The citation list:
Thank you for your guidance and we will consider to use `verbose` argument to show the list.
(Currently, we show the citations as a property of Python classes.)

Japan dataset:
Your dataset is excellent and I think the number of cases agrees with my dataset. I'm collecting raw data from [Ministry of Health, Labour and Welfare HP](https://www.mhlw.go.jp/english/) and upload to [GitHub: lisphilar/covid19-sir/data](https://github.com/lisphilar/covid19-sir/tree/master/data) and [Kaggle:COVID-19 dataset in Japan](https://www.kaggle.com/lisphilar/covid19-dataset-in-japan).

I also collected metadata, including the number of beds (Japan has five types of beds). If it contributes to your dataset, I will provide it under CC BY-4.0 or ask you cite it as follows.
Lisphilar (2020), COVID-19 dataset in Japan, GitHub repository, https://github.com/lisphilar/covid19-sir/data/japan

I will be back here to notify the update of the package as soon as possible.
Best Regards,
Lisphilar

**Comment by lisphilar** [comment]
CovsirPhy was updated and data source was successfully swiched to COVID-19 Data Hub.
Thank you for your collaboration.

**Comment by eguidotti** [comment]
Great, just added your package in the use cases. 
It will be live in a couple of hours. Enjoy :)

**Comment by eguidotti** [comment]
Hello @lisphilar, I'd like to notify you that we updated the covid19dh python package you are using in CovsirPhy.
The `covid19` function is now returning both data (raw data by default) and data sources. The `cite` function has been deprecated. Please have a look [here](https://pypi.org/project/covid19dh/).
Also, it would be great if you could update the citation to the data hub from the working paper to the published paper you can find in the previous link.
Many thanks!

**Comment by lisphilar** [comment]
Dear @eguidotti ,
Thank you for your kind notice and congratulations for publishing your paper!!

I will release new version of CovsirPhy to use the newest version of your package and cite your paper as Guidotti, E., Ardia, D., (2020), "COVID-19 Data Hub", Journal of Open Source Software 5(51):2376, doi: 10.21105/joss.02376.

Thank you!

**Comment by lisphilar** [comment]
Dear @eguidotti ,
See you again and thank you for maintaining COVID-19 Data Hub!
This is not the thread for discussion, but can we create a database for influenza?
How do you think about this idea?
Thank you.

**Comment by eguidotti** [comment]
Hello @lisphilar, thank you for your message and your idea.
Maintaining this data hub is already quite time consuming and intensive.
Unfortunately I don't think I would be able to extend it to influenza in the near future. 
But please feel free to re-use the open source code in this repo! In case you find it useful to create something similar for e.g. influenza. That would be great. 
If you like to discuss it further of have some other idea you can find my email address on my [public profile](https://github.com/eguidotti).
Thanks!

**Comment by lisphilar** [comment]
Dear @eguidotti ,
Thank you for your kind response and sorry for my late reply.
I will consider development of influenza dataset, but knowledge and resources are limited.
I will read your codes in COVID-19 Data Hub.
Thank you again for your maintenance of this great database!
