### ISSUE TITLE
No Updates?

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#88]
The level-3 data set has not been updated since July 2. This is the second substantial delay in the past 10 days. Will updates be more regular in the future? My needs require the freshest data possible. Thank you, Ken

**Comment by eguidotti** [comment]
Hello @kenshermock, I can't see any error in the data update this time and everything seems fine.
Which data do you see out of date? Level 3 for which country? 
Thank you

**Comment by kenshermock** [comment]
Level 3 for the U.S. I just checked again and there are observations up to July 4, but the values for July 3 and 4 are equal to July 2 for every county.

Thanks, Ken

**Comment by eguidotti** [comment]
The hub is updated hourly, but some providers are not. We are using the data from  [NYTimes](https://github.com/nytimes/covid-19-data) for US level 3.

It seems to me they updated the data up to 3rd July. The 4th of July is filled with our package. If interested in the raw data without any processing, you can [download](https://covid19datahub.io/articles/data.html) the `rawdata` files or use the argument `raw=TRUE` if using our [R](https://github.com/covid19datahub/R)/[python](https://github.com/covid19datahub/Python) packages.

**Comment by eguidotti** [comment]
It seems this is fixed. Feel free to reopen if needed.
Best,
-- Emanuele

**Comment by kenshermock** [comment]
Level 2 data have not updated since August 2. The NYTimes source data are updated to 8/4 at levels 2 and 3 was of noon on 8/5, as I write this.

**Comment by eguidotti** [comment]
Fixed. And added an automated test to spot similar bugs in the future.
Many thanks!
