### ISSUE TITLE
Data by region from Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [covid19datahub/COVID19#89]
Since Mar 15, 2020 I've been collecting the data that has been published in press releases, etc. from MINSA (the Ministry of Health of Peru).

You can find that in: https://github.com/jmcastagnetto/covid-19-peru-data/

Also, once they started releasing some data as open data, I've also put a repository with some data cleaning and concordance scripts at: https://github.com/jmcastagnetto/covid-19-peru-limpiar-datos-minsa

The second repo is not as complete as the first one.

**Comment by eguidotti** [comment]
Hi @jmcastagnetto, thank you for your message!
I'm afraid I didn't understand which is the best data provider to integrate in our project.
Which source would you recommend? 

- https://github.com/jmcastagnetto/covid-19-peru-data/
- https://github.com/jmcastagnetto/covid-19-peru-limpiar-datos-minsa
- https://www.datosabiertos.gob.pe/search/field_topic/covid-19-917

Which are the pros and cons of the sources? Many thanks!

**Comment by jmcastagnetto** [comment]
Hi @emanuele-guidotti 

> Hi @jmcastagnetto, thank you for your message!
> I'm afraid I didn't understand which is the best data provider to integrate in our project.
> Which source would you recommend?
> 
>     * https://github.com/jmcastagnetto/covid-19-peru-data/

This data has been collected since early March 2020, and published in github since mid March 2020, using the official notes and other public sources from the Peruvian Ministry of Health. I am still using those information sources, fixing some standardization issues and adding some regional geolocation (UBIGEO codes) to the dataset (e.g. https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-data-con-ubigeos.csv)

The main datasets there have information (by region) on positive cases, total cases, and number of cases for type of testing: PCR, serological, and PCR + serological (the official information on the latter has been spotty).

Also, it collects information on ICU usage (overall, no by region, that is not yet publicly available), data on number of people hospitalized, use of mechanical respirators, medical discharges, diagnoses, etc. (also overall, not by region) 

So, if you need regional information (sub-national) the `covid-19-peru-data.csv` (or the one with geo codes, see above), will be of use for your repo. Be aware that there is no detail of cases per region, just the total per region per date here.

I tend to update this daily at night, after the public info is updated. Hopefully at some point there will be an official historical data resource with enough data and consistency, so we all can rely on that instead (I will be very happy when that happens :-)

>     * https://github.com/jmcastagnetto/covid-19-peru-limpiar-datos-minsa
>     * https://www.datosabiertos.gob.pe/search/field_topic/covid-19-917
> 

These two are related, my repo pulls daily updates from the open data, and does cleaning on inconsistencies. There are two sources I am using in my repo:

- The details of positive cases, which include information on sex, age, date of result for the test, type of test and location at a more detailed level (level 3 sub-national).
- The details on official deaths by COVID-19 (sex, age, date of decease, location)

In my code, I try to fix obvious errors, like, dates in multiple formats (dd/mm/yyyy vs yyyy/mm/dd), add an estimate of the age (if the date of birth exists).

Also, I use the data on sex, age and location to try and correlate positive cases with deaths. The ID that both datasets use are not compatible, so the reconstruction is partial and with obvious caveats.

What I found out is that the counts per region (and the overall counts) taken from this, more detail, official dataset for cases, does not completely match the figures given in the official notes. See for example: https://twitter.com/jmcastagnetto/status/1264633781060866050

---

There is also another repo I did not mention, that cleans up the data from the general deaths dataset (SINADEF) that is publicly published too. That one is bigger and contains fields with presumptive causes of death (6 fields), since ~2017. That data has more inconsistencies like, problems with assignment of ages, incomplete or erroneous locations, misspellings of causes, etc.  interest is that even with that, it is possible to tag the entries with possible COVID-19 cause. The URL is https://github.com/jmcastagnetto/sinadef-peru-fallecimientos, and is also updated daily.

Let me know if you need more details.

Cheers

**Comment by eguidotti** [comment]
Hi @jmcastagnetto, many thanks for your very detailed reply.
I will try to integrate the data from https://github.com/jmcastagnetto/covid-19-peru-data/

**Comment by jmcastagnetto** [comment]
Hello @emanuele-guidotti. If you need more details or something is amiss, just let me know. Glad the datasets can be useful.

**Comment by eguidotti** [comment]
Hello @jmcastagnetto, I'm adding your data to the hub. I have a couple of questions regarding your [file on hospitalizations](https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-detalle-hospitalizados.csv):

- it seems to me these are daily counts, correct? Or are they cumulative counts?
- do ICU patients (intensive therapy) correspond to the column `uci`? I can see only a couple of numbers at the beginning but it seems this is no longer updated
- do `ventilacion_mecanica` represent patients requiring ventilation? It seems that this numer corresponds to ICU on wikipedia: right panel -> severe cases -> icu https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Peru 

Could you try to run the following and double check the data I integrated?

```R
remotes::install_github("covid19datahub/COVID19")

library("COVID19")
x <- covid19("PER", level = 1)
x <- covid19("PER", level = 2)
```
I added the reference to your data as follows: 
_COVID-19 Peru Data Repository (2020), https://github.com/jmcastagnetto/covid-19-peru-data_
Please let me know if you prefer a different citation.

Many thanks for your contribution!

**Comment by jmcastagnetto** [comment]
Hi @eguidotti 

> Hello @jmcastagnetto, I'm adding your data to the hub. I have a couple of questions regarding your [file on hospitalizations](https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-detalle-hospitalizados.csv):
> 
>     * it seems to me these are daily counts, correct? Or are they cumulative counts?

These are taken (mainly) from what MINSA publishes at the "Sala Situacional..." (vide infra) daily, which are "point in time snapshots", so is the daily counts (situation at the time of report). They are not cumulative values AFAIK.

"Sala Situacional de COVID 19 en Perú": https://covid19.minsa.gob.pe/sala_situacional.asp

> 
>     * do ICU patients (intensive therapy) correspond to the column `uci`? I can see only a couple of numbers at the beginning but it seems this is no longer updated
> 

Yes, UCI is the spanish acronym for ICU in english. They appeared initially in the daily communiques from the Ministry of Health (not consistently) but then they stopped appearing explicitly. Instead they are putting (in the "Sala Situacional...") the counts by diagnostic state of people hospitalized, or whether they need or not mechanical ventilation, without explicitly indicating those who are are or not in ICU (I understand you can be in ICU but maybe not need ventilation).

One thing I aimed to track also, was the data on the evolution of the available beds in ICU. IIRC at the beginning of the epidemic outbreak here in Peru, we had ~100 ICU beds with ventilators, but now we got ~1447 beds (almos 14.5x increase since March).
That data is in https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covi-19-peru-camas-uci.csv, you will see the number of occupied and unoccupied ICU beds reported since 2020-04-27 (the first time this was published in public sources), separated by the health system where the bed is located. In Peru we still have parallel public health systems: ESSALUD (depends of the Ministry of Work -- like the Secretary of Labor in USA), MINSA (Ministry of Health), Police and Armed Forces (`ffaa_pnp`) and regional governments, apart from the private hospitals.

Perhaps that last dataset might be a good choice to get the daily totals of people in ICU (and how many more ICU beds are still open)

>     * do `ventilacion_mecanica` represent patients requiring ventilation? It seems that this numer corresponds to ICU on wikipedia: right panel -> severe cases -> icu https://en.wikipedia.org/wiki/COVID-19_pandemic_in_Peru
>  

Yes, "ventilación mecánica" are those who require mechanical ventilation and are usually patientes that are in ICU, so it might be considered equivalent, because of the way the pandemic is been handled in Peru. As this criteria, seems to me, has change since the beginning of the first cases here, I decided not to merge those columns, but you can do the equivalency for consistency with other datasets.

> 
> Could you try to run the following and double check the data I integrated?
> 
> ```r
>
> library("COVID19")
> x <- covid19("PER", level = 1)
> x <- covid19("PER", level = 2)
> ```
> 

That looks good indeed. I wish I knew if somewhere there is a dataset with the info missing in some columns (school closing, workplace closings, etc.). If I get more info on that, I'll let you know.

> I added the reference to your data as follows:
> _COVID-19 Peru Data Repository (2020), https://github.com/jmcastagnetto/covid-19-peru-data_
> Please let me know if you prefer a different citation.

That is good enough for me, and hope the data I am collecting can he useful. Mi little bit to help with this global crisis.

> 
> Many thanks for your contribution!

Thank you for the big effort of consolidating and organizing data from many sources in a coherent and useful manner.

Cheers!

**Comment by jmcastagnetto** [comment]
One idea you've given me, is to add the lat,lon for the capital of departamento (admin level 2). I have a good official source for that, and will look into adding that this weekend.

**Comment by eguidotti** [comment]
Hi @jmcastagnetto, thank you for your detailed reply. This is very useful.

Regarding ICU, I noticed that the numbers contained in https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-camas-uci.csv -> estado: en uso -> total are the same of "ventilación mecánica" in the other file. Do you think I can proceed and set ICU equal to "ventilación mecánica" for Peru?

> I wish I knew if somewhere there is a dataset with the info missing in some columns (school closing, workplace closings, etc.). If I get more info on that, I'll let you know.

It seems to me the policies are already there (school closing, workplace closings, etc.). What data do you think is missing?

> One idea you've given me, is to add the lat,lon for the capital of departamento (admin level 2). I have a good official source for that, and will look into adding that this weekend.

Great, please let me know if you happen to add lat/lng to your dataset. I'd be happy to add them as well in the data hub

**Comment by jmcastagnetto** [comment]
Hi @eguidotti 

> Hi @jmcastagnetto, thank you for your detailed reply. This is very useful.
> 
> Regarding ICU, I noticed that the numbers contained in https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-camas-uci.csv -> estado: en uso -> total are the same of "ventilación mecánica" in the other file. Do you think I can proceed and set ICU equal to "ventilación mecánica" for Peru?
> 

Yes, go ahead.

> > I wish I knew if somewhere there is a dataset with the info missing in some columns (school closing, workplace closings, etc.). If I get more info on that, I'll let you know.
> 
> It seems to me the policies are already there (school closing, workplace closings, etc.). What data do you think is missing?
> 

My mistake, I was looking at the first 25 lines of the data (was using R on the terminal), now I have looked at in toto, and yep, that info is there.

> > One idea you've given me, is to add the lat,lon for the capital of departamento (admin level 2). I have a good official source for that, and will look into adding that this weekend.
> 
> Great, please let me know if you happen to add lat/lng to your dataset. I'd be happy to add them as well in the data hub

Will do.

Have a nice weekend.

**Comment by jmcastagnetto** [comment]
@eguidotti 

Just got around to adding some more fields. Because there are some other projects using the basic data set (https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-data.csv), I've added the extra fields to the file: https://github.com/jmcastagnetto/covid-19-peru-data/blob/main/datos/covid-19-peru-data-augmented.csv

Basically, this is the final list of columns on the latter data file:

- country: Peru
- iso3c: PER
- region: Departament (Region) of Perú
- region_orig: Original region denomination (there were some changes in the public data from 2020-07-05 onwards)
- ubigeo: UBIGEO (peruvian code for the region)
- iso_3166_2_code: ISO-3166-2 code for the region
- date: YYYY-MM-DD
- confirmed: confirmed cases
- deaths: deaths
- recovered: recovered cases (only as a national total)
- total_tests: total number of tests
- negative_tests: tests that were negative
- pcr_test_positive: positive tests detected by PCR
- serological_test_positive: positive tests detected by "rapid tests"
- pcr_serological_test_positive: positive cases detected by both PCR and "rapid tests" (a few have been reported)
- zone: geographical zone (North, South, Center)
- pop2019: region population (2019)
- surface: surface area (Km2)
- capital: city capital of the region
- altitude: altitude of the city capital
- lat: latitude of the city capital
- lon: longitude of the city capital

**Comment by eguidotti** [comment]
Hi @jmcastagnetto, thank you for the new file!
I integrated the new data and added you in the contributors section on the [website](https://covid19datahub.io/articles/contributors.html). Your name will appear in a couple of hours.

I couldn't find your email address to award you the [badge](https://eu.badgr.com/public/badges/MC89IAjTTLGs3geP3xHjRw) for the contribution.
If you like to have it, just let me know your email adress here or with a private message on [Slack](https://join.slack.com/t/covid19datahub/shared_invite/zt-e921sryd-Sb97p~skvovQM6NuXFUNCw).

Thanks!

**Comment by jmcastagnetto** [comment]
@eguidotti :+1:  -- sent you my email via Slack.

This issue can be closed if you want. 

Cheers.
