### ISSUE TITLE
coding of OxCGRT policy measures

### ISSUE THREAD

**Issue by flaxter** [covid19datahub/COVID19#97]
Is this intentional or perhaps I'm missing something? The geographic flags from OxCGRT aren't included (reasonable simplification, in my opinion), but that means that, e.g. Italy's schools are listed as closed on 23 February (true for Lombardy, presumably), rather than 4 March. Perhaps worth including the acaps dataset as an alternative? (https://www.acaps.org/projects/covid19/data)

**Comment by flaxter** [comment]
(just checked acaps---doesn't help in this case!)

**Comment by eguidotti** [comment]
Hi @flaxter, thank you for your suggestion.

Yes we thought to include policies at national level only. The policies that are being impemented are very heterogeneous and I'm afraid we won't be able to maintain such a dataset as we'd need to match each policy with the corresponding region and/or city. On the other hand, adding the flag of warning may be an option yes.

The ACAPS dataset looks very nice. I hope it would be easy enough for researchers working on this kind of policies to merge them with our dataset for the specific regions of interest. 
Are you working on something in particular?

**Comment by flaxter** [comment]
Thanks for your reply. Currently doing a small sensitivity analysis on my
Nature paper (Flaxman et al, 2020
https://www.nature.com/articles/s41586-020-2405-7) extending to 150+
countries and trying various specifications for R(t) in terms of OxCGRT,
ACAPS, mobility, etc. We'll hopefully have a convenient R interface to your
package with our epidemia package soon:
https://imperialcollegelondon.github.io/epidemia/

ACAPS takes a bit of work to clean-up and merge, so built-in capabilities
might be nice. If I get my code tidied up, I will try to do a pull
request...

**Comment by eguidotti** [comment]
>  If I get my code tidied up, I will try to do a pull request...

That would be of great help! Thank you.
In the meanwhile I'm going to close this issue.

If you like to showcase your work here, just let me know when ready: https://covid19datahub.io/articles/usage.html

Thanks!
-- Emanuele
