### ISSUE TITLE
No Recent Updates

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#99]
No updates to level 2 or 3 data sets since August 16. Thank you.

**Comment by GuidoMaggio** [comment]
I do not see updates for most of Countries as well. E.g. in Europe only France and Italy have new confirmed cases on 17/08
Thanks

**Comment by eguidotti** [comment]
Looking into this. Thanks

**Comment by eguidotti** [comment]
Fixed.

The server was not installing the latest version of the package correctly.
Sorry about that and thanks for the notification (again!)

**Comment by kenshermock** [comment]
My pleasure! Thank you for all the work you do to provide us with such a helpful data set!  Ken

**Comment by GuidoMaggio** [comment]
Thanks for reacting so quickly
all seems to work
